# Pré-processamento de Dados, do dataset de Teste, a ser usado no Desenvolvimento dos Modelos Preditivos
---

## A) Importação das Bibliotecas
---

### 1. Pacotes baixados:
---

In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import RobustScaler, MinMaxScaler

### 2. Pacote Predexan:
---

In [2]:
import sys
import os

caminho_predexan = os.path.abspath(os.path.join(os.getcwd(), '../..'))

if caminho_predexan not in sys.path:
    sys.path.append(caminho_predexan)

print(f"Buscando em: {caminho_predexan}")
print(f"Pastas encontradas: {os.listdir(caminho_predexan)}")

import predexan.graficos as pg
import predexan.metricas as pm
import predexan.preproc as pp

Buscando em: C:\Users\rmaca\PUC_eixo7\projeto\pmv-si-2026-1-pe7-t3-g1-pesquisaexperimentacao-2026-1\src
Pastas encontradas: ['.ipynb_checkpoints', 'analise_exploratoria_pre_processamento', 'dataset', 'imagens', 'modelos', 'predexan', 'README.md']

## B) Criação do DataFrame
---

O DataFrame, `df` é criado usando a função de `Pandas` específica para arquivos `.parquet`, chamada `pd.read_csv()`, uma vez que o dataset `UNSW_NB15_training-set.parquet` está neste formato.

In [3]:
df= pd.read_parquet('../../dataset/original/UNSW_NB15_testing-set.parquet')
df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.09375,180363632.0,...,0,0,1,1,0,0,0,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.00000,881000000.0,...,0,0,1,1,0,0,0,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.00000,854400000.0,...,0,0,1,1,0,0,0,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.65625,600000000.0,...,0,0,2,1,0,0,0,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.00000,850400000.0,...,0,0,2,1,0,0,0,0,Normal,0

## C) Manipulação dos Dados
---

### 1 - Conferência dos atributos, renomeação e correção da tipagem
---

O método `.info()` mostra todos os atributos (colunas) do DataFrame, junto à quantidade de valores não nulos e tipagem de cada um, além de gasto de memória do df.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dur                82332 non-null  float32
 1   proto              82332 non-null  category
 2   service            82332 non-null  category
 3   state              82332 non-null  category
 4   spkts              82332 non-null  int16
 5   dpkts              82332 non-null  int16
 6   sbytes             82332 non-null  int32
 7   dbytes             82332 non-null  int32
 8   rate               82332 non-null  float32
 9   sload              82332 non-null  float32
 10  dload              82332 non-null  float32
 11  sloss              82332 non-null  int16
 12  dloss              82332 non-null  int16
 13  sinpkt             82332 non-null  float32
 14  dinpkt             82332 non-null  float32
 15  sjit               82332 non-null  float32
 16  djit               82332 non-null  float32
 17  swin               82332 non-null  int16
 18  stcpb              82332 non-null  int64
 19  dtcpb              82332 non-null  int64
 20  dwin               82332 non-null  int16
 21  tcprtt             82332 non-null  float32
 22  synack             82332 non-null  float32
 23  ackdat             82332 non-null  float32
 24  smean              82332 non-null  int16
 25  dmean              82332 non-null  int16
 26  trans_depth        82332 non-null  int16
 27  response_body_len  82332 non-null  int32
 28  ct_src_dport_ltm   82332 non-null  int8
 29  ct_dst_sport_ltm   82332 non-null  int8
 30  is_ftp_login       82332 non-null  int8
 31  ct_ftp_cmd         82332 non-null  int8
 32  ct_flw_http_mthd   82332 non-null  int8
 33  is_sm_ips_ports    82332 non-null  int8
 34  attack_cat         82332 non-null  category
 35  label              82332 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 8.0 MB

#### 1.1. Renomeando os atributos
---

A adequação dos nomes dos atributos é feita com o atributo `.rename()`. Para tal, há a necessidade de explicitar o parâmetro `columns` e passar como argumento os nomes antigos e novos dos atributos, em formato de `dicionário` ou `JSON`.

É feita para uma maior comodidade e compreensão no contexto de `Manipulação de Dados` e `Análise Exploratória de Dados`.

In [5]:
df = df.rename(columns={
    'dur':'duracao_conexao_seg',
    'proto':'protocolo_rede',
    'service':'servico_conexao',
    'state':'estado_conexao',
    'spkts':'num_pacotes_origem',
    'dpkts':'num_pacotes_destino',
    'sbytes':'total_bytes_origem',
    'dbytes':'total_bytes_destino',
    'rate':'taxa_pacote',
    'sload':'carga_origem',
    'dload':'carga_destino',
    'sloss':'pacotes_perdidos_origem',
    'dloss':'pacotes_perdidos_destino',
    'sinpkt':'tempo_medio_pacote_origem',
    'dinpkt':'bytes_por_pacote_destino',
    'sjit':'var_lat_pacotes_origem',
    'djit':'var_lat_pacotes_destino',
    'swin':'tamanho_janela_tcp_origem',
    'stcpb':'num_sequencia_tcp_origem',
    'dtcpb':'num_sequencia_tcp_destino',
    'dwin':'tamanho_janela_tcp_destino',
    'tcprtt':'rtt_handshake_tcp',
    'synack':'tempo_syn_synack',
    'ackdat':'tempo_synack_ack',
    'smean':'tamanho_medio_pacotes_origem',
    'dmean':'tamanho_medio_pacotes_destino',
    'trans_depth':'profundidade_transacao_http',
    'response_body_len':'tamanho_corpo_resposta_http',
    'ct_src_dport_ltm':"conexoes_recentes_ip_porta_destino",
    'ct_dst_sport_ltm':"conexoes_recentes_ip_porta_origem",
    'is_ftp_login':'ftp_autenticada',
    'ct_ftp_cmd':'num_comandos_ftp',
    'ct_flw_http_mthd':'num_metodos_http',
    'is_sm_ips_ports':'ip_porta_origem_destino_iguais',
    'attack_cat':'categoria_ataque',
    'label':'label'
})

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   duracao_conexao_seg                 82332 non-null  float32
 1   protocolo_rede                      82332 non-null  category
 2   servico_conexao                     82332 non-null  category
 3   estado_conexao                      82332 non-null  category
 4   num_pacotes_origem                  82332 non-null  int16
 5   num_pacotes_destino                 82332 non-null  int16
 6   total_bytes_origem                  82332 non-null  int32
 7   total_bytes_destino                 82332 non-null  int32
 8   taxa_pacote                         82332 non-null  float32
 9   carga_origem                        82332 non-null  float32
 10  carga_destino                       82332 non-null  float32
 11  pacotes_perdidos_origem             82332 non-null  int16
 12  pacotes_perdidos_destino            82332 non-null  int16
 13  tempo_medio_pacote_origem           82332 non-null  float32
 14  bytes_por_pacote_destino            82332 non-null  float32
 15  var_lat_pacotes_origem              82332 non-null  float32
 16  var_lat_pacotes_destino             82332 non-null  float32
 17  tamanho_janela_tcp_origem           82332 non-null  int16
 18  num_sequencia_tcp_origem            82332 non-null  int64
 19  num_sequencia_tcp_destino           82332 non-null  int64
 20  tamanho_janela_tcp_destino          82332 non-null  int16
 21  rtt_handshake_tcp                   82332 non-null  float32
 22  tempo_syn_synack                    82332 non-null  float32
 23  tempo_synack_ack                    82332 non-null  float32
 24  tamanho_medio_pacotes_origem        82332 non-null  int16
 25  tamanho_medio_pacotes_destino       82332 non-null  int16
 26  profundidade_transacao_http         82332 non-null  int16
 27  tamanho_corpo_resposta_http         82332 non-null  int32
 28  conexoes_recentes_ip_porta_destino  82332 non-null  int8
 29  conexoes_recentes_ip_porta_origem   82332 non-null  int8
 30  ftp_autenticada                     82332 non-null  int8
 31  num_comandos_ftp                    82332 non-null  int8
 32  num_metodos_http                    82332 non-null  int8
 33  ip_porta_origem_destino_iguais      82332 non-null  int8
 34  categoria_ataque                    82332 non-null  category
 35  label                               82332 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 8.0 MB

#### 1.2. Conferência de Valores e Nulos
---

In [7]:
for col in df.columns:
    print(f'\nValores do atributo {col}:\n')
    print(df[col].value_counts())
    print('\n')
    print('='*40)

Valores do atributo duracao_conexao_seg:

duracao_conexao_seg
0.000009    5546
0.000008    4938
0.000003    4111
0.000004    3336
0.000011    3112
            ...
0.524434       1
0.947039       1
0.811914       1
5.167410       1
1.106101       1
Name: count, Length: 39888, dtype: int64


========================================

Valores do atributo protocolo_rede:

protocolo_rede
tcp     43095
udp     29418
unas     3515
arp       987
ospf      676
        ...
wsn        32
xtp        32
zero       32
ib         31
igmp       30
Name: count, Length: 131, dtype: int64


========================================

Valores do atributo servico_conexao:

servico_conexao
-           47153
dns         21367
http         8287
smtp         1851
ftp          1552
ftp-data     1396
pop3          423
ssh           204
ssl            30
snmp           29
dhcp           26
radius          9
irc             5
Name: count, dtype: int64


========================================

Valores do atributo estado_conexao:

estado_conexao
FIN    39339
INT    34163
CON     6982
REQ     1842
ACC        4
CLO        1
RST        1
Name: count, dtype: int64


========================================

Valores do atributo num_pacotes_origem:

num_pacotes_origem
2       36982
10      16386
12       3093
14       2648
16       2489
        ...
788         1
522         1
2730        1
1159        1
83          1
Name: count, Length: 420, dtype: int64


========================================

Valores do atributo num_pacotes_destino:

num_pacotes_destino
0       36006
8        9465
6        7464
2        5448
10       3746
        ...
804         1
704         1
2194        1
1163        1
1432        1
Name: count, Length: 436, dtype: int64


========================================

Valores do atributo total_bytes_origem:

total_bytes_origem
114       18158
200        7187
534        2376
146        2140
1540       1661
          ...
432           1
434           1
3376          1
135414        1
138067        1
Name: count, Length: 4489, dtype: int64


========================================

Valores do atributo total_bytes_destino:

total_bytes_destino
0         36006
268        7141
354        5497
178        2138
86         1905
          ...
119490        1
9030          1
9148          1
9232          1
15365         1
Name: count, Length: 4034, dtype: int64


========================================

Valores do atributo taxa_pacote:

taxa_pacote
111111.109375    5603
125000.000000    4941
333333.312500    3957
90909.093750     3281
250000.000000    3220
                 ...
28.602266           1
15.838841           1
18.474861           1
25.351192           1
24.410067           1
Name: count, Length: 40557, dtype: int64


========================================

Valores do atributo carga_origem:

carga_origem
5.066666e+07    3271
5.700000e+07    2586
1.520000e+08    1997
1.140000e+08    1994
4.145454e+07    1854
                ...
8.084907e+03       1
4.477112e+03       1
5.222228e+03       1
2.117719e+05       1
1.241044e+05       1
Name: count, Length: 42873, dtype: int64


========================================

Valores do atributo carga_destino:

carga_destino
0.000000         36013
657433.062500       27
678741.687500       25
664799.250000       24
676806.125000       24
                 ...
3417.017334          1
1892.213501          1
2207.130127          1
1546.616211          1
2242.109863          1
Name: count, Length: 40614, dtype: int64


========================================

Valores do atributo pacotes_perdidos_origem:

pacotes_perdidos_origem
0      39320
2      19304
7       6005
4       3739
3       3575
       ...
99         1
97         1
107        1
101        1
96         1
Name: count, Length: 253, dtype: int64


========================================

Valores do atributo pacotes_perdidos_destino:

pacotes_perdidos_destino
0       41204
1       15745
2        6211
4        4119
8        2233
        ...
400         1
350         1
1091        1
535         1
714         1
Name: count, Length: 311, dtype: int64


========================================

Valores do atributo tempo_medio_pacote_origem:

tempo_medio_pacote_origem
0.009000      5657
0.008000      5088
0.011000      4395
0.003000      4024
0.010000      3791
              ...
54.837555        1
105.122223       1
83.216331        1
48.287766        1
55.880051        1
Name: count, Length: 39949, dtype: int64


========================================

Valores do atributo bytes_por_pacote_destino:

bytes_por_pacote_destino
0.000000      36015
0.008000       1331
0.009000        904
0.007000        641
0.002000        508
              ...
88.782799         1
170.938995        1
138.888596        1
221.155212        1
143.699997        1
Name: count, Length: 37596, dtype: int64


========================================

Valores do atributo var_lat_pacotes_origem:

var_lat_pacotes_origem
0.000000       38650
32.106724         23
55.640575         22
29.430767         21
38.804020         21
               ...
2932.416260        1
6914.180664        1
4368.102539        1
9709.118164        1
4798.130859        1
Name: count, Length: 39911, dtype: int64


========================================

Valores do atributo var_lat_pacotes_destino:

var_lat_pacotes_destino
0.000000        41552
196.928177         20
70.142296          11
12723.927734        9
7579.062988         9
                ...
142.553497          1
308.874573          1
195.623779          1
559.560486          1
190.980820          1
Name: count, Length: 38355, dtype: int64


========================================

Valores do atributo tamanho_janela_tcp_origem:

tamanho_janela_tcp_origem
255    43086
0      39237
156        1
202        1
99         1
5          1
67         1
154        1
52         1
245        1
43         1
Name: count, dtype: int64


========================================

Valores do atributo num_sequencia_tcp_origem:

num_sequencia_tcp_origem
0             40881
3738475984       16
1057528719       12
3536959022        9
2395243350        9
              ...
2572742215        1
3714205944        1
3487870721        1
2309382861        1
1072535109        1
Name: count, Length: 39219, dtype: int64


========================================

Valores do atributo num_sequencia_tcp_destino:

num_sequencia_tcp_destino
0             40894
1460955064       24
3773804157       18
463094449        12
1649858926        9
              ...
3690476903        1
3164085634        1
2884385558        1
4150989117        1
3284291478        1
Name: count, Length: 39108, dtype: int64


========================================

Valores do atributo tamanho_janela_tcp_destino:

tamanho_janela_tcp_destino
255    41415
0      40904
27         2
81         1
160        1
77         1
171        1
137        1
164        1
33         1
209        1
12         1
46         1
125        1
Name: count, dtype: int64


========================================

Valores do atributo rtt_handshake_tcp:

rtt_handshake_tcp
0.000000    41127
0.000665       85
0.000678       80
0.000667       80
0.000675       78
            ...
0.134360        1
0.172227        1
0.237125        1
0.140691        1
0.173208        1
Name: count, Length: 26130, dtype: int64


========================================

Valores do atributo tempo_syn_synack:

tempo_syn_synack
0.000000    41127
0.000548      120
0.000551      113
0.000535      107
0.000543      106
            ...
0.057270        1
0.056739        1
0.083616        1
0.117467        1
0.100191        1
Name: count, Length: 24934, dtype: int64


========================================

Valores do atributo tempo_synack_ack:

tempo_synack_ack
0.000000    41160
0.000134      487
0.000133      471
0.000135      462
0.000136      398
            ...
0.059884        1
0.053846        1
0.119658        1
0.059860        1
0.073017        1
Name: count, Length: 24020, dtype: int64


========================================

Valores do atributo tamanho_medio_pacotes_origem:

tamanho_medio_pacotes_origem
57      18924
100      7356
53       3754
73       2242
56       2137
        ...
1256        1
1084        1
515         1
1015        1
523         1
Name: count, Length: 1282, dtype: int64


========================================

Valores do atributo tamanho_medio_pacotes_destino:

tamanho_medio_pacotes_destino
0       36006
45       7243
44       6283
89       2260
43       2143
        ...
1079        1
1237        1
610         1
1377        1
1033        1
Name: count, Length: 1222, dtype: int64


========================================

Valores do atributo profundidade_transacao_http:

profundidade_transacao_http
0      74750
1       7548
2         28
3          2
131        1
9          1
4          1
8          1
Name: count, dtype: int64


========================================

Valores do atributo tamanho_corpo_resposta_http:

tamanho_corpo_resposta_http
0         76675
3924       1042
83          361
524288      149
109          99
          ...
23627         1
260116        1
15            1
2084          1
1492          1
Name: count, Length: 1190, dtype: int64


========================================

Valores do atributo conexoes_recentes_ip_porta_destino:

conexoes_recentes_ip_porta_destino
1     43181
2     11661
3      5173
4      4645
6      2295
7      2289
25     1661
18     1610
5      1154
43      909
14      610
10      478
16      469
8       458
11      413
9       374
20      346
23      329
17      306
15      302
13      277
12      271
19      265
35      232
21      202
24      200
32      182
22      182
26      163
40      161
27      159
42      155
37      155
39      137
38      136
29      104
41      102
28      100
33       99
31       93
36       88
34       81
30       72
45       16
47       10
59       10
48        6
44        5
52        5
50        1
Name: count, dtype: int64


========================================

Valores do atributo conexoes_recentes_ip_porta_origem:

conexoes_recentes_ip_porta_origem
1     53883
2      6524
4      5127
3      4499
25     2251
18     2127
6      1063
14      618
16      565
10      453
13      440
8       437
15      436
17      402
11      400
9       374
12      330
20      330
5       329
22      311
19      307
23      288
24      287
21      255
7       238
27       17
28       16
37        7
32        7
26        5
31        3
33        2
38        1
Name: count, dtype: int64


========================================

Valores do atributo ftp_autenticada:

ftp_autenticada
0    81654
1      674
2        4
Name: count, dtype: int64


========================================

Valores do atributo num_comandos_ftp:

num_comandos_ftp
0    81652
1      670
2       10
Name: count, dtype: int64


========================================

Valores do atributo num_metodos_http:

num_metodos_http
0     74752
1      6908
4       478
9       126
16       32
2        18
12       12
6         6
Name: count, dtype: int64


========================================

Valores do atributo ip_porta_origem_destino_iguais:

ip_porta_origem_destino_iguais
0    81416
1      916
Name: count, dtype: int64


========================================

Valores do atributo categoria_ataque:

categoria_ataque
Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
Name: count, dtype: int64


========================================

Valores do atributo label:

label
1    45332
0    37000
Name: count, dtype: int64


========================================

Valores nulos geram erro de processamento, por isso devem ser tratados.

No dataset escolhido, nenhuma coluna apresentou tais valores.

In [8]:
df.isna().sum()

duracao_conexao_seg                   0
protocolo_rede                        0
servico_conexao                       0
estado_conexao                        0
num_pacotes_origem                    0
num_pacotes_destino                   0
total_bytes_origem                    0
total_bytes_destino                   0
taxa_pacote                           0
carga_origem                          0
carga_destino                         0
pacotes_perdidos_origem               0
pacotes_perdidos_destino              0
tempo_medio_pacote_origem             0
bytes_por_pacote_destino              0
var_lat_pacotes_origem                0
var_lat_pacotes_destino               0
tamanho_janela_tcp_origem             0
num_sequencia_tcp_origem              0
num_sequencia_tcp_destino             0
tamanho_janela_tcp_destino            0
rtt_handshake_tcp                     0
tempo_syn_synack                      0
tempo_synack_ack                      0
tamanho_medio_pacotes_origem          0
tamanho_medio_pacotes_destino         0
profundidade_transacao_http           0
tamanho_corpo_resposta_http           0
conexoes_recentes_ip_porta_destino    0
conexoes_recentes_ip_porta_origem     0
ftp_autenticada                       0
num_comandos_ftp                      0
num_metodos_http                      0
ip_porta_origem_destino_iguais        0
categoria_ataque                      0
label                                 0
dtype: int64

#### 1.3. Conferência de registros duplicados em todo o DataFrame
---

Manter registros completos duplicados na base de dados que será usada para testes do modelo preditivo pode levar a `overfitting`, onde o modelo acaba "decorando" padrões específicos, que pode levar a um enviezamento de respostas. Portanto, duplicatas devem ser excluídas.

No dataset, há a presença de `32361` registros duplicados.

#### 1.4. Conferência de valores únicos por atributo
---

O dataset possui 11 atributos que, por terem poucos valores únicos poderiam ser divididos em `categorias`:
| Atributo | Número de valores únicos |
| :---: | :---: |
| `servico_conexao` | 13 |
| `estado_conexao` | 9 |
| `tamanho_janela_tcp_origem` | 13 |
| `tamanho_janela_tcp_destino` | 7 |
| `profundidade_transacao_http` | 11 |
| `ftp_autenticada` | 4 |
| `num_comandos_ftp` | 4 |
| `num_metodos_http` | 11 |
| `ip_porta_origem_destino_iguais` | 2 |
| `categoria_ataque` | 10 |
| `label` | 2 |

Os demais atributos possuem diversos valores únicos, não podendo ser divididos e, categorias de maneira mais simples.

In [9]:
df.nunique()

duracao_conexao_seg                   39888
protocolo_rede                          131
servico_conexao                          13
estado_conexao                            7
num_pacotes_origem                      420
num_pacotes_destino                     436
total_bytes_origem                     4489
total_bytes_destino                    4034
taxa_pacote                           40557
carga_origem                          42873
carga_destino                         40614
pacotes_perdidos_origem                 253
pacotes_perdidos_destino                311
tempo_medio_pacote_origem             39949
bytes_por_pacote_destino              37596
var_lat_pacotes_origem                39911
var_lat_pacotes_destino               38355
tamanho_janela_tcp_origem                11
num_sequencia_tcp_origem              39219
num_sequencia_tcp_destino             39108
tamanho_janela_tcp_destino               14
rtt_handshake_tcp                     26130
tempo_syn_synack                      24934
tempo_synack_ack                      24020
tamanho_medio_pacotes_origem           1282
tamanho_medio_pacotes_destino          1222
profundidade_transacao_http               8
tamanho_corpo_resposta_http            1190
conexoes_recentes_ip_porta_destino       50
conexoes_recentes_ip_porta_origem        33
ftp_autenticada                           3
num_comandos_ftp                          3
num_metodos_http                          8
ip_porta_origem_destino_iguais            2
categoria_ataque                         10
label                                     2
dtype: int64

#### 1.5. Exclusão de registros duplicados
---

Manter colunas e dados desnecessários é perigoso, pois não trazem nenhum tipo de novas informações relevantes ou características que agregam valor ao modelo preditivo, mas podem ocasionar `enviesamento` e `ruídos` que podem confundí-lo e reduzir sua eficiência e confiabilidade.

O dataset possui `82332 ` registros no total, mas destes, `32361` são duplicados e devem, portanto, ser apagados.

In [10]:
df.duplicated().sum()

np.int64(32361)

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.shape)

(49971, 36)

#### 1.6. Ajuste das classes dos atributos categóricos
---

Há a necessidade de se ajustar as classes raras, pois estas podem ser prejudiciais ao modelo, levando ao `overfitting`. Um cenário possível associar uma classe x, que apareceu apenas uma vez, a `0` ou `1`.

##### 1.6.1. Atributo protocolo_rede
---

- **Original**:

In [13]:
df['protocolo_rede'].value_counts()

protocolo_rede
tcp          39642
udp           8003
unas           389
arp            294
ospf           187
             ...
wsn             10
xtp             10
zero            10
ib               9
ipv6-opts        6
Name: count, Length: 131, dtype: int64

- **Após limitação induzida**:

In [14]:
limite = 1000

frequencias = df['protocolo_rede'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['protocolo_rede'] = df['protocolo_rede'].astype('str').replace(protocolos_raros, 'outros')

print(df['protocolo_rede'].value_counts())

protocolo_rede
tcp       39642
udp        8003
outros     2326
Name: count, dtype: int64

##### 1.6.2. Atributo servico_conexao
---

- **Original**:

In [15]:
df['servico_conexao'].value_counts()

servico_conexao
-           33363
http         7906
dns          3812
smtp         1758
ftp          1288
ftp-data     1177
pop3          381
ssh           204
ssl            30
snmp           22
dhcp           19
radius          6
irc             5
Name: count, dtype: int64

- **Após limitação induzida**:

In [16]:
limite = 1000

frequencias = df['servico_conexao'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['servico_conexao'] = df['servico_conexao'].astype('str').replace(protocolos_raros, 'outros')

print(df['servico_conexao'].value_counts())

servico_conexao
-           33363
http         7906
dns          3812
smtp         1758
ftp          1288
ftp-data     1177
outros        667
Name: count, dtype: int64

##### 1.6.3. Atributo servico_conexao
---

- **Original**:

In [17]:
df['estado_conexao'].value_counts()

estado_conexao
FIN    37280
CON     6436
INT     5863
REQ      386
ACC        4
CLO        1
RST        1
Name: count, dtype: int64

- **Após limitação induzida**:

In [18]:
limite = 1000

frequencias = df['estado_conexao'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['estado_conexao'] = df['estado_conexao'].astype('str').replace(protocolos_raros, 'outros')

print(df['estado_conexao'].value_counts())

estado_conexao
FIN       37280
CON        6436
INT        5863
outros      392
Name: count, dtype: int64

##### 1.6.4. Atributo categoria_ataque
---

- **Original**:

In [19]:
df['categoria_ataque'].value_counts()

categoria_ataque
Normal            31610
Exploits           7482
Fuzzers            4415
Reconnaissance     2127
Generic            1643
DoS                1598
Analysis            386
Shellcode           370
Backdoor            296
Worms                44
Name: count, dtype: int64

Não será limitado por ser um `target`. É necessário ter todos os dados detalhados desse atributo.

#### 1.7. Adequando a tipagem dos dados relativos aos atributos
---

É necessária a adequação da tipagem dos dados relativos aos atributos, para que todo o processo de `Análise Exploratória de Dados` e `Treino e Teste dos Modelos de Aprendizado Supervisionado` aconteçam da melhor maneira.

Tanto a `Matriz de Correlação de Spearman` e a biblioteca `Scikit-Learn` operam somente com valores numéricos. Em caso de haver dados das classes `str`, `object`, `datetime` e `category`, a matriz pode desconsiderá-los e o sklearn pode retornar erro.

Há a necessidade de tratar os atributos categóricos que tenham a tipagem `str` ou `object`. São muito relevantes tanto para as análises descritivas, quanto para as preditivas, por agruparem dados que possam ter grande correlação com o diagnóstico de ataque cibernético. Contudo, para serem usados, devem ser transformados em números.

Para este notebook, que tem por finalidade o `pré-processamento dos dados` que irão ser usados no desenvolvimento dos modelos preditivos, a escolha de encoding é o `OneHotEncoding`, por ser mais adequado a modelos como `Regressão Logística` e `Multi Layer Perceptron (MLP)` por não sugerir prioridade nos dados, mas aumenta a dimensionalidade.

##### 1.6.1. Encoding com OneHotEncoding
---

In [20]:
atr_categoricos = ['protocolo_rede', 'servico_conexao', 'estado_conexao', 'categoria_ataque', 'label']

In [21]:
encoder = OneHotEncoder()

dados_transformados = encoder.fit_transform(df[atr_categoricos]).toarray()

df_codificado = pd.DataFrame(dados_transformados, columns=encoder.get_feature_names_out(atr_categoricos), index=df.index
)


df_codificado

,protocolo_rede_outros,protocolo_rede_tcp,protocolo_rede_udp,servico_conexao_-,servico_conexao_dns,servico_conexao_ftp,servico_conexao_ftp-data,servico_conexao_http,servico_conexao_outros,servico_conexao_smtp,...,categoria_ataque_DoS,categoria_ataque_Exploits,categoria_ataque_Fuzzers,categoria_ataque_Generic,categoria_ataque_Normal,categoria_ataque_Reconnaissance,categoria_ataque_Shellcode,categoria_ataque_Worms,label_0,label_1
0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82314,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
82317,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
82319,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
82323,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
82328,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

##### 1.6.2. Criação do df_final para uso nos modelos
---

In [22]:
df_copia = df.copy()

df_copia = df_copia.drop(columns=atr_categoricos)

atr_nao_categoricos = df_copia.columns.to_list()

df_final = pd.concat([df_copia, df_codificado], axis=1)
df_final.info()

<class 'pandas.DataFrame'>
Index: 49971 entries, 0 to 82328
Data columns (total 57 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   duracao_conexao_seg                 49971 non-null  float32
 1   num_pacotes_origem                  49971 non-null  int16
 2   num_pacotes_destino                 49971 non-null  int16
 3   total_bytes_origem                  49971 non-null  int32
 4   total_bytes_destino                 49971 non-null  int32
 5   taxa_pacote                         49971 non-null  float32
 6   carga_origem                        49971 non-null  float32
 7   carga_destino                       49971 non-null  float32
 8   pacotes_perdidos_origem             49971 non-null  int16
 9   pacotes_perdidos_destino            49971 non-null  int16
 10  tempo_medio_pacote_origem           49971 non-null  float32
 11  bytes_por_pacote_destino            49971 non-null  float32
 12  var_lat_pacotes_origem              49971 non-null  float32
 13  var_lat_pacotes_destino             49971 non-null  float32
 14  tamanho_janela_tcp_origem           49971 non-null  int16
 15  num_sequencia_tcp_origem            49971 non-null  int64
 16  num_sequencia_tcp_destino           49971 non-null  int64
 17  tamanho_janela_tcp_destino          49971 non-null  int16
 18  rtt_handshake_tcp                   49971 non-null  float32
 19  tempo_syn_synack                    49971 non-null  float32
 20  tempo_synack_ack                    49971 non-null  float32
 21  tamanho_medio_pacotes_origem        49971 non-null  int16
 22  tamanho_medio_pacotes_destino       49971 non-null  int16
 23  profundidade_transacao_http         49971 non-null  int16
 24  tamanho_corpo_resposta_http         49971 non-null  int32
 25  conexoes_recentes_ip_porta_destino  49971 non-null  int8
 26  conexoes_recentes_ip_porta_origem   49971 non-null  int8
 27  ftp_autenticada                     49971 non-null  int8
 28  num_comandos_ftp                    49971 non-null  int8
 29  num_metodos_http                    49971 non-null  int8
 30  ip_porta_origem_destino_iguais      49971 non-null  int8
 31  protocolo_rede_outros               49971 non-null  float64
 32  protocolo_rede_tcp                  49971 non-null  float64
 33  protocolo_rede_udp                  49971 non-null  float64
 34  servico_conexao_-                   49971 non-null  float64
 35  servico_conexao_dns                 49971 non-null  float64
 36  servico_conexao_ftp                 49971 non-null  float64
 37  servico_conexao_ftp-data            49971 non-null  float64
 38  servico_conexao_http                49971 non-null  float64
 39  servico_conexao_outros              49971 non-null  float64
 40  servico_conexao_smtp                49971 non-null  float64
 41  estado_conexao_CON                  49971 non-null  float64
 42  estado_conexao_FIN                  49971 non-null  float64
 43  estado_conexao_INT                  49971 non-null  float64
 44  estado_conexao_outros               49971 non-null  float64
 45  categoria_ataque_Analysis           49971 non-null  float64
 46  categoria_ataque_Backdoor           49971 non-null  float64
 47  categoria_ataque_DoS                49971 non-null  float64
 48  categoria_ataque_Exploits           49971 non-null  float64
 49  categoria_ataque_Fuzzers            49971 non-null  float64
 50  categoria_ataque_Generic            49971 non-null  float64
 51  categoria_ataque_Normal             49971 non-null  float64
 52  categoria_ataque_Reconnaissance     49971 non-null  float64
 53  categoria_ataque_Shellcode          49971 non-null  float64
 54  categoria_ataque_Worms              49971 non-null  float64
 55  label_0                             49971 non-null  float64
 56  label_1                             49971 non-null  float64
dtypes: float32(11), float64(26), int16(9), int32(3), int64(2), int8(6)
memory usage: 14.9 MB

##### 1.6.3. Transformar valores em float64
---

In [23]:
for x in df_final.columns:
    df_final[x] = df_final[x].astype(float)
    print(f'O atributo {x} teve o tipo convertido para {df_final[x].dtype}')

df_final = df_final.copy()

O atributo duracao_conexao_seg teve o tipo convertido para float64
O atributo num_pacotes_origem teve o tipo convertido para float64
O atributo num_pacotes_destino teve o tipo convertido para float64
O atributo total_bytes_origem teve o tipo convertido para float64
O atributo total_bytes_destino teve o tipo convertido para float64
O atributo taxa_pacote teve o tipo convertido para float64
O atributo carga_origem teve o tipo convertido para float64
O atributo carga_destino teve o tipo convertido para float64
O atributo pacotes_perdidos_origem teve o tipo convertido para float64
O atributo pacotes_perdidos_destino teve o tipo convertido para float64
O atributo tempo_medio_pacote_origem teve o tipo convertido para float64
O atributo bytes_por_pacote_destino teve o tipo convertido para float64
O atributo var_lat_pacotes_origem teve o tipo convertido para float64
O atributo var_lat_pacotes_destino teve o tipo convertido para float64
O atributo tamanho_janela_tcp_origem teve o tipo convertido para float64
O atributo num_sequencia_tcp_origem teve o tipo convertido para float64
O atributo num_sequencia_tcp_destino teve o tipo convertido para float64
O atributo tamanho_janela_tcp_destino teve o tipo convertido para float64
O atributo rtt_handshake_tcp teve o tipo convertido para float64
O atributo tempo_syn_synack teve o tipo convertido para float64
O atributo tempo_synack_ack teve o tipo convertido para float64
O atributo tamanho_medio_pacotes_origem teve o tipo convertido para float64
O atributo tamanho_medio_pacotes_destino teve o tipo convertido para float64
O atributo profundidade_transacao_http teve o tipo convertido para float64
O atributo tamanho_corpo_resposta_http teve o tipo convertido para float64
O atributo conexoes_recentes_ip_porta_destino teve o tipo convertido para float64
O atributo conexoes_recentes_ip_porta_origem teve o tipo convertido para float64
O atributo ftp_autenticada teve o tipo convertido para float64
O atributo num_comandos_ftp teve o tipo convertido para float64
O atributo num_metodos_http teve o tipo convertido para float64
O atributo ip_porta_origem_destino_iguais teve o tipo convertido para float64
O atributo protocolo_rede_outros teve o tipo convertido para float64
O atributo protocolo_rede_tcp teve o tipo convertido para float64
O atributo protocolo_rede_udp teve o tipo convertido para float64
O atributo servico_conexao_- teve o tipo convertido para float64
O atributo servico_conexao_dns teve o tipo convertido para float64
O atributo servico_conexao_ftp teve o tipo convertido para float64
O atributo servico_conexao_ftp-data teve o tipo convertido para float64
O atributo servico_conexao_http teve o tipo convertido para float64
O atributo servico_conexao_outros teve o tipo convertido para float64
O atributo servico_conexao_smtp teve o tipo convertido para float64
O atributo estado_conexao_CON teve o tipo convertido para float64
O atributo estado_conexao_FIN teve o tipo convertido para float64
O atributo estado_conexao_INT teve o tipo convertido para float64
O atributo estado_conexao_outros teve o tipo convertido para float64
O atributo categoria_ataque_Analysis teve o tipo convertido para float64
O atributo categoria_ataque_Backdoor teve o tipo convertido para float64
O atributo categoria_ataque_DoS teve o tipo convertido para float64
O atributo categoria_ataque_Exploits teve o tipo convertido para float64
O atributo categoria_ataque_Fuzzers teve o tipo convertido para float64
O atributo categoria_ataque_Generic teve o tipo convertido para float64
O atributo categoria_ataque_Normal teve o tipo convertido para float64
O atributo categoria_ataque_Reconnaissance teve o tipo convertido para float64
O atributo categoria_ataque_Shellcode teve o tipo convertido para float64
O atributo categoria_ataque_Worms teve o tipo convertido para float64
O atributo label_0 teve o tipo convertido para float64
O atributo label_1 teve o tipo convertido para float64

In [24]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 49971 entries, 0 to 82328
Data columns (total 57 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   duracao_conexao_seg                 49971 non-null  float64
 1   num_pacotes_origem                  49971 non-null  float64
 2   num_pacotes_destino                 49971 non-null  float64
 3   total_bytes_origem                  49971 non-null  float64
 4   total_bytes_destino                 49971 non-null  float64
 5   taxa_pacote                         49971 non-null  float64
 6   carga_origem                        49971 non-null  float64
 7   carga_destino                       49971 non-null  float64
 8   pacotes_perdidos_origem             49971 non-null  float64
 9   pacotes_perdidos_destino            49971 non-null  float64
 10  tempo_medio_pacote_origem           49971 non-null  float64
 11  bytes_por_pacote_destino            49971 non-null  float64
 12  var_lat_pacotes_origem              49971 non-null  float64
 13  var_lat_pacotes_destino             49971 non-null  float64
 14  tamanho_janela_tcp_origem           49971 non-null  float64
 15  num_sequencia_tcp_origem            49971 non-null  float64
 16  num_sequencia_tcp_destino           49971 non-null  float64
 17  tamanho_janela_tcp_destino          49971 non-null  float64
 18  rtt_handshake_tcp                   49971 non-null  float64
 19  tempo_syn_synack                    49971 non-null  float64
 20  tempo_synack_ack                    49971 non-null  float64
 21  tamanho_medio_pacotes_origem        49971 non-null  float64
 22  tamanho_medio_pacotes_destino       49971 non-null  float64
 23  profundidade_transacao_http         49971 non-null  float64
 24  tamanho_corpo_resposta_http         49971 non-null  float64
 25  conexoes_recentes_ip_porta_destino  49971 non-null  float64
 26  conexoes_recentes_ip_porta_origem   49971 non-null  float64
 27  ftp_autenticada                     49971 non-null  float64
 28  num_comandos_ftp                    49971 non-null  float64
 29  num_metodos_http                    49971 non-null  float64
 30  ip_porta_origem_destino_iguais      49971 non-null  float64
 31  protocolo_rede_outros               49971 non-null  float64
 32  protocolo_rede_tcp                  49971 non-null  float64
 33  protocolo_rede_udp                  49971 non-null  float64
 34  servico_conexao_-                   49971 non-null  float64
 35  servico_conexao_dns                 49971 non-null  float64
 36  servico_conexao_ftp                 49971 non-null  float64
 37  servico_conexao_ftp-data            49971 non-null  float64
 38  servico_conexao_http                49971 non-null  float64
 39  servico_conexao_outros              49971 non-null  float64
 40  servico_conexao_smtp                49971 non-null  float64
 41  estado_conexao_CON                  49971 non-null  float64
 42  estado_conexao_FIN                  49971 non-null  float64
 43  estado_conexao_INT                  49971 non-null  float64
 44  estado_conexao_outros               49971 non-null  float64
 45  categoria_ataque_Analysis           49971 non-null  float64
 46  categoria_ataque_Backdoor           49971 non-null  float64
 47  categoria_ataque_DoS                49971 non-null  float64
 48  categoria_ataque_Exploits           49971 non-null  float64
 49  categoria_ataque_Fuzzers            49971 non-null  float64
 50  categoria_ataque_Generic            49971 non-null  float64
 51  categoria_ataque_Normal             49971 non-null  float64
 52  categoria_ataque_Reconnaissance     49971 non-null  float64
 53  categoria_ataque_Shellcode          49971 non-null  float64
 54  categoria_ataque_Worms              49971 non-null  float64
 55  label_0                             49971 non-null  float64
 56  label_1                             49971 non-null  float64
dtypes: float64(57)
memory usage: 22.1 MB

### 2. Normalização de Features
---

Como visto no `Notebook de Explicação de Pré-Processamento e Análise Exploratória de Dados`, a distribuição dos dados se mostra `não normal`. Desta forma, o tipo de normalização mais adequado, de modo geral, é o `RobustScaler`, que é baseado em `IQR`. Contudo, também foi utilizado `MinMaxScaler` em alguns atributos:

1. `RobustScaler`:
   - Utilizado em atributos volumétricos: Bytes, Pacotes, Duração, Carga, RTT e Variância de Latência;
   - Presença de muitos outliers e variância muito expressiva, já que dados de volume brutos de rede são naturalmente assimétricos. Uma conexão normal pode trocar 500 bytes, enquanto um download legítimo ou um ataque de negação de serviço (DoS/DDoS) pode transferir 12 milhões de bytes na mesma janela de tempo;
   - Utiliza a Mediana e o Intervalo Interquartil (IQR) em vez da média e do máximo. Isso garante que a massa de dados normais fique bem distribuída em torno de zero, enquanto os picos (outliers) ganham valores proporcionalmente altos (como 5415.28). O modelo consegue diferenciar um tráfego comum de uma anomalia sem perder a sensibilidade dos dados menores.

2. `MinMaxScaler`:
    - Utilizado em atributos de aplicação e contagem: Métodos HTTP, Comandos FTP, Conexões Recentes, Tamanho de Janela TCP e Flags;
    - Limites bem definidos: essas variáveis possuem tetos previsíveis e controlados pelo protocolo. O número de métodos HTTP disparados em uma única sessão varia em uma escala menor. O tamanho da janela TCP possui um limite rígido do sistema (0 a 255). Não existem outliers muito grandes e distantes;
    - O MinMaxScaler mapeia com eficiência o menor valor para 0.0 e o maior valor real (seja 4, 30 ou 255) para 1.0, por conta da previsibilidade das variáveis. Isso traz todas as contagens para a mesma ordem de grandeza do restante do dataset de forma mais homogênea.

#### 2.1. Separando os atributos
---

##### 2.1.1. Atributos não categóricos
---

In [25]:
atr_nao_categoricos = df.drop(columns=atr_categoricos).columns.to_list()

##### 2.1.2. Atributos para RobustScaler
---

In [26]:
colunas_para_remover = atr_categoricos + [
    'tamanho_janela_tcp_origem', 'tamanho_janela_tcp_destino', 'profundidade_transacao_http',
    'tamanho_corpo_resposta_http', 'conexoes_recentes_ip_porta_destino', 'conexoes_recentes_ip_porta_origem',
    'ftp_autenticada', 'num_comandos_ftp', 'num_metodos_http', 'ip_porta_origem_destino_iguais'
]
atr_robust_scaler = df.drop(columns=colunas_para_remover).columns.to_list()

##### 2.1.3. Atributos para MinMaxScaler
---

In [27]:
atr_min_max_scaler = df[['tamanho_janela_tcp_origem',
    'tamanho_janela_tcp_destino',
    'profundidade_transacao_http',
    'tamanho_corpo_resposta_http',
    'conexoes_recentes_ip_porta_destino',
    'conexoes_recentes_ip_porta_origem',
    'ftp_autenticada',
    'num_comandos_ftp',
    'num_metodos_http',
    'ip_porta_origem_destino_iguais']].columns.to_list()

#### 2.2. Normalizando atributos
---

##### 2.2.1. Carregando os escalonadores aprendidos no Pré-Processamento de treino
---

- **RobustScaler**:

In [28]:
escalonador_robusto = joblib.load('../escalonadores/escalonador_robusto.pkl')

- **MinMaxScaler**:

In [29]:
escalonador_minmax = joblib.load('../escalonadores/escalonador_minmax.pkl')

##### 2.2.2. RobustScaler
---

In [30]:
# Transforma o bloco de colunas inteiro de uma vez para respeitar o formato esperado pelo Scikit-Learn e evitar erros de dimensionalidade no .transform()
df_robust_transformado = pd.DataFrame(
    escalonador_robusto.transform(df_final[atr_robust_scaler]), 
    columns=atr_robust_scaler, 
    index=df_final.index
)

# Iteração por todos os atributos, mostrando os valores antes e depois da Normalização e apenas transformando os dados que já foram aprendidos
for col in atr_robust_scaler:

    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'\n\n   -> Atributo {col.upper()}:\n')
    print(f'O atributo {col} possui amplitude entre {valor_min} e {valor_max} e magnitude {faixa} antes da Normalização com {escalonador_robusto}.\n')
    
    
    df_final.loc[:, col] = df_robust_transformado[col]
    
    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'O atributo {col} foi normalizado. Sua amplitude atual está entre {valor_min} e {valor_max}. Já sua magnitude é {faixa}.\n')

# Consolida as alterações no DataFrame e previne o aviso "PerformanceWarning: DataFrame is highly fragmented"
df_final = df_final.copy()

   -> Atributo DURACAO_CONEXAO_SEG:

O atributo duracao_conexao_seg possui amplitude entre 0.0 e 59.9999885559082 e magnitude 59.9999885559082 antes da Normalização com RobustScaler().

O atributo duracao_conexao_seg foi normalizado. Sua amplitude atual está entre -0.44357456734279826 e 59.43035021560755. Já sua magnitude é 59.87392478295035.



   -> Atributo NUM_PACOTES_ORIGEM:

O atributo num_pacotes_origem possui amplitude entre 1.0 e 10646.0 e magnitude 10645.0 antes da Normalização com RobustScaler().

O atributo num_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.5625 e 664.75. Já sua magnitude é 665.3125.



   -> Atributo NUM_PACOTES_DESTINO:

O atributo num_pacotes_destino possui amplitude entre 0.0 e 11018.0 e magnitude 11018.0 antes da Normalização com RobustScaler().

O atributo num_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.5 e 688.125. Já sua magnitude é 688.625.



   -> Atributo TOTAL_BYTES_ORIGEM:

O atributo total_bytes_origem possui amplitude entre 24.0 e 14355774.0 e magnitude 14355750.0 antes da Normalização com RobustScaler().

O atributo total_bytes_origem foi normalizado. Sua amplitude atual está entre -0.4277360066833751 e 5996.126148705096. Já sua magnitude é 5996.55388471178.



   -> Atributo TOTAL_BYTES_DESTINO:

O atributo total_bytes_destino possui amplitude entre 0.0 e 14657531.0 e magnitude 14657531.0 antes da Normalização com RobustScaler().

O atributo total_bytes_destino foi normalizado. Sua amplitude atual está entre -0.20493247210804463 e 4303.239283617147. Já sua magnitude é 4303.444216089255.



   -> Atributo TAXA_PACOTE:

O atributo taxa_pacote possui amplitude entre 0.0 e 1000000.0 e magnitude 1000000.0 antes da Normalização com RobustScaler().

O atributo taxa_pacote foi normalizado. Sua amplitude atual está entre -0.02273333602547066 e 356.06816390032577. Já sua magnitude é 356.0908972363512.



   -> Atributo CARGA_ORIGEM:

O atributo carga_origem possui amplitude entre 0.0 e 5268000256.0 e magnitude 5268000256.0 antes da Normalização com RobustScaler().

O atributo carga_origem foi normalizado. Sua amplitude atual está entre -0.057231631081325486 e 8294.141531483323. Já sua magnitude é 8294.198763114404.



   -> Atributo CARGA_DESTINO:

O atributo carga_destino possui amplitude entre 0.0 e 20821108.0 e magnitude 20821108.0 antes da Normalização com RobustScaler().

O atributo carga_destino foi normalizado. Sua amplitude atual está entre -0.016328903360192524 e 34.078326484587734. Já sua magnitude é 34.094655387947924.



   -> Atributo PACOTES_PERDIDOS_ORIGEM:

O atributo pacotes_perdidos_origem possui amplitude entre 0.0 e 5319.0 e magnitude 5319.0 antes da Normalização com RobustScaler().

O atributo pacotes_perdidos_origem foi normalizado. Sua amplitude atual está entre -0.4 e 1063.4. Já sua magnitude é 1063.8000000000002.



   -> Atributo PACOTES_PERDIDOS_DESTINO:

O atributo pacotes_perdidos_destino possui amplitude entre 0.0 e 5507.0 e magnitude 5507.0 antes da Normalização com RobustScaler().

O atributo pacotes_perdidos_destino foi normalizado. Sua amplitude atual está entre -0.3333333333333333 e 917.5. Já sua magnitude é 917.8333333333334.



   -> Atributo TEMPO_MEDIO_PACOTE_ORIGEM:

O atributo tempo_medio_pacote_origem possui amplitude entre 0.0 e 60009.9921875 e magnitude 60009.9921875 antes da Normalização com RobustScaler().

O atributo tempo_medio_pacote_origem foi normalizado. Sua amplitude atual está entre -0.36133865318408365 e 757.8754070510212. Já sua magnitude é 758.2367457042053.



   -> Atributo BYTES_POR_PACOTE_DESTINO:

O atributo bytes_por_pacote_destino possui amplitude entre 0.0 e 57739.23828125 e magnitude 57739.23828125 antes da Normalização com RobustScaler().

O atributo bytes_por_pacote_destino foi normalizado. Sua amplitude atual está entre -0.3478855071532177 e 654.0763072272458. Já sua magnitude é 654.4241927343991.



   -> Atributo VAR_LAT_PACOTES_ORIGEM:

O atributo var_lat_pacotes_origem possui amplitude entre 0.0 e 1483830.875 e magnitude 1483830.875 antes da Normalização com RobustScaler().

O atributo var_lat_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.34416657687734703 e 318.7128884528455. Já sua magnitude é 319.05705502972285.



   -> Atributo VAR_LAT_PACOTES_DESTINO:

O atributo var_lat_pacotes_destino possui amplitude entre 0.0 e 463199.25 e magnitude 463199.25 antes da Normalização com RobustScaler().

O atributo var_lat_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.400681236510594 e 2272.383023845713. Já sua magnitude é 2272.7837050822236.



   -> Atributo NUM_SEQUENCIA_TCP_ORIGEM:

O atributo num_sequencia_tcp_origem possui amplitude entre 0.0 e 4294949667.0 e magnitude 4294949667.0 antes da Normalização com RobustScaler().

O atributo num_sequencia_tcp_origem foi normalizado. Sua amplitude atual está entre -0.5597790686381059 e 0.9974611712098677. Já sua magnitude é 1.5572402398479737.



   -> Atributo NUM_SEQUENCIA_TCP_DESTINO:

O atributo num_sequencia_tcp_destino possui amplitude entre 0.0 e 4294880717.0 e magnitude 4294880717.0 antes da Normalização com RobustScaler().

O atributo num_sequencia_tcp_destino foi normalizado. Sua amplitude atual está entre -0.558730231133571 e 1.001637839966318. Já sua magnitude é 1.560368071099889.



   -> Atributo RTT_HANDSHAKE_TCP:

O atributo rtt_handshake_tcp possui amplitude entre 0.0 e 3.821465015411377 e magnitude 3.821465015411377 antes da Normalização com RobustScaler().

O atributo rtt_handshake_tcp foi normalizado. Sua amplitude atual está entre -0.009828122445103204 e 29.195324055790017. Já sua magnitude é 29.20515217823512.



   -> Atributo TEMPO_SYN_SYNACK:

O atributo tempo_syn_synack possui amplitude entre 0.0 e 3.22678804397583 e magnitude 3.22678804397583 antes da Normalização com RobustScaler().

O atributo tempo_syn_synack foi normalizado. Sua amplitude atual está entre -0.016261070130149765 e 47.99016777600971. Já sua magnitude é 48.00642884613986.



   -> Atributo TEMPO_SYNACK_ACK:

O atributo tempo_synack_ack possui amplitude entre 0.0 e 2.9287779331207275 e magnitude 2.9287779331207275 antes da Normalização com RobustScaler().

O atributo tempo_synack_ack foi normalizado. Sua amplitude atual está entre -0.00403792688985175 e 47.875280679371194. Já sua magnitude é 47.879318606261045.



   -> Atributo TAMANHO_MEDIO_PACOTES_ORIGEM:

O atributo tamanho_medio_pacotes_origem possui amplitude entre 24.0 e 1504.0 e magnitude 1480.0 antes da Normalização com RobustScaler().

O atributo tamanho_medio_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.8082191780821918 e 19.465753424657535. Já sua magnitude é 20.273972602739725.



   -> Atributo TAMANHO_MEDIO_PACOTES_DESTINO:

O atributo tamanho_medio_pacotes_destino possui amplitude entre 0.0 e 1500.0 e magnitude 1500.0 antes da Normalização com RobustScaler().

O atributo tamanho_medio_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.5925925925925926 e 10.518518518518519. Já sua magnitude é 11.11111111111111.

##### 2.2.2. MinMaxScaler
---

In [31]:
# Transforma o bloco de colunas inteiro de uma vez para respeitar o formato esperado pelo Scikit-Learn e evitar erros de dimensionalidade no .transform()
df_minmax_transformado = pd.DataFrame(
    escalonador_minmax.transform(df_final[atr_min_max_scaler]), 
    columns=atr_min_max_scaler, 
    index=df_final.index
)

# Iteração por todos os atributos, mostrando os valores antes e depois da Normalização e apenas transformando os dados que já foram aprendidos
for col in atr_min_max_scaler:

    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'\n\n   -> Atributo {col.upper()}:\n')
    print(f'O atributo {col} possui amplitude entre {valor_min} e {valor_max} e magnitude {faixa} antes da Normalização com {escalonador_minmax}.\n')
    
    df_final.loc[:, col] = df_minmax_transformado[col]
    
    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'O atributo {col} foi normalizado. Sua amplitude atual está entre {valor_min} e {valor_max}. Já sua magnitude é {faixa}.\n')

# Consolida as alterações no DataFrame e previne o aviso "PerformanceWarning: DataFrame is highly fragmented"
df_final = df_final.copy()

   -> Atributo TAMANHO_JANELA_TCP_ORIGEM:

O atributo tamanho_janela_tcp_origem possui amplitude entre 0.0 e 255.0 e magnitude 255.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_janela_tcp_origem foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo TAMANHO_JANELA_TCP_DESTINO:

O atributo tamanho_janela_tcp_destino possui amplitude entre 0.0 e 255.0 e magnitude 255.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_janela_tcp_destino foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo PROFUNDIDADE_TRANSACAO_HTTP:

O atributo profundidade_transacao_http possui amplitude entre 0.0 e 131.0 e magnitude 131.0 antes da Normalização com MinMaxScaler().

O atributo profundidade_transacao_http foi normalizado. Sua amplitude atual está entre 0.0 e 0.7616279069767442. Já sua magnitude é 0.7616279069767442.



   -> Atributo TAMANHO_CORPO_RESPOSTA_HTTP:

O atributo tamanho_corpo_resposta_http possui amplitude entre 0.0 e 5242880.0 e magnitude 5242880.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_corpo_resposta_http foi normalizado. Sua amplitude atual está entre 0.0 e 0.7994564242818298. Já sua magnitude é 0.7994564242818298.



   -> Atributo CONEXOES_RECENTES_IP_PORTA_DESTINO:

O atributo conexoes_recentes_ip_porta_destino possui amplitude entre 1.0 e 59.0 e magnitude 58.0 antes da Normalização com MinMaxScaler().

O atributo conexoes_recentes_ip_porta_destino foi normalizado. Sua amplitude atual está entre 0.0 e 1.16. Já sua magnitude é 1.16.



   -> Atributo CONEXOES_RECENTES_IP_PORTA_ORIGEM:

O atributo conexoes_recentes_ip_porta_origem possui amplitude entre 1.0 e 38.0 e magnitude 37.0 antes da Normalização com MinMaxScaler().

O atributo conexoes_recentes_ip_porta_origem foi normalizado. Sua amplitude atual está entre 0.0 e 0.8222222222222222. Já sua magnitude é 0.8222222222222222.



   -> Atributo FTP_AUTENTICADA:

O atributo ftp_autenticada possui amplitude entre 0.0 e 2.0 e magnitude 2.0 antes da Normalização com MinMaxScaler().

O atributo ftp_autenticada foi normalizado. Sua amplitude atual está entre 0.0 e 0.5. Já sua magnitude é 0.5.



   -> Atributo NUM_COMANDOS_FTP:

O atributo num_comandos_ftp possui amplitude entre 0.0 e 2.0 e magnitude 2.0 antes da Normalização com MinMaxScaler().

O atributo num_comandos_ftp foi normalizado. Sua amplitude atual está entre 0.0 e 0.5. Já sua magnitude é 0.5.



   -> Atributo NUM_METODOS_HTTP:

O atributo num_metodos_http possui amplitude entre 0.0 e 16.0 e magnitude 16.0 antes da Normalização com MinMaxScaler().

O atributo num_metodos_http foi normalizado. Sua amplitude atual está entre 0.0 e 0.5333333333333333. Já sua magnitude é 0.5333333333333333.



   -> Atributo IP_PORTA_ORIGEM_DESTINO_IGUAIS:

O atributo ip_porta_origem_destino_iguais possui amplitude entre 0.0 e 1.0 e magnitude 1.0 antes da Normalização com MinMaxScaler().

O atributo ip_porta_origem_destino_iguais foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.

## E) Criação do Dataset Pré-processado de Teste
---

Este dataset será usado no teste dos modelos preditivos.

In [32]:
df.to_parquet('../../dataset/pre_processado/teste_pre_processado.parquet')