
# Pré-processamento de Dados, do dataset de Treino, a ser usado no Desenvolvimento dos Modelos Preditivos
---

## A) Importação das Bibliotecas
---

### 1. Pacotes baixados:
---

In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import RobustScaler, MinMaxScaler

### 2. Pacote Predexan:
---

In [2]:
import sys
import os

caminho_predexan = os.path.abspath(os.path.join(os.getcwd(), '../..'))

if caminho_predexan not in sys.path:
    sys.path.append(caminho_predexan)

print(f"Buscando em: {caminho_predexan}")
print(f"Pastas encontradas: {os.listdir(caminho_predexan)}")

import predexan.graficos as pg
import predexan.metricas as pm
import predexan.preproc as pp

Buscando em: C:\Users\rmaca\PUC_eixo7\projeto\pmv-si-2026-1-pe7-t3-g1-pesquisaexperimentacao-2026-1\src
Pastas encontradas: ['.ipynb_checkpoints', 'analise_exploratoria_pre_processamento', 'dataset', 'imagens', 'modelos', 'predexan', 'README.md']

## B) Criação do DataFrame
---

O DataFrame, `df` é criado usando a função de `Pandas` específica para arquivos `.parquet`, chamada `pd.read_csv()`, uma vez que o dataset `UNSW_NB15_training-set.parquet` está neste formato.

In [3]:
df= pd.read_parquet('../../dataset/original/UNSW_NB15_training-set.parquet')
df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087486,14158.942383,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473373,8395.112305,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.271851,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.178955,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.499023,...,0,0,2,1,0,0,0,0,Normal,0

## C) Manipulação dos Dados
---

### 1 - Conferência dos atributos, renomeação e correção da tipagem
---

O método `.info()` mostra todos os atributos (colunas) do DataFrame, junto à quantidade de valores não nulos e tipagem de cada um, além de gasto de memória do df.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float32
 1   proto              175341 non-null  category
 2   service            175341 non-null  category
 3   state              175341 non-null  category
 4   spkts              175341 non-null  int16
 5   dpkts              175341 non-null  int16
 6   sbytes             175341 non-null  int32
 7   dbytes             175341 non-null  int32
 8   rate               175341 non-null  float32
 9   sload              175341 non-null  float32
 10  dload              175341 non-null  float32
 11  sloss              175341 non-null  int16
 12  dloss              175341 non-null  int16
 13  sinpkt             175341 non-null  float32
 14  dinpkt             175341 non-null  float32
 15  sjit               175341 non-null  float32
 16  djit               175341 non-null  float32
 17  swin               175341 non-null  int16
 18  stcpb              175341 non-null  int64
 19  dtcpb              175341 non-null  int64
 20  dwin               175341 non-null  int16
 21  tcprtt             175341 non-null  float32
 22  synack             175341 non-null  float32
 23  ackdat             175341 non-null  float32
 24  smean              175341 non-null  int16
 25  dmean              175341 non-null  int16
 26  trans_depth        175341 non-null  int16
 27  response_body_len  175341 non-null  int32
 28  ct_src_dport_ltm   175341 non-null  int8
 29  ct_dst_sport_ltm   175341 non-null  int8
 30  is_ftp_login       175341 non-null  int8
 31  ct_ftp_cmd         175341 non-null  int8
 32  ct_flw_http_mthd   175341 non-null  int8
 33  is_sm_ips_ports    175341 non-null  int8
 34  attack_cat         175341 non-null  category
 35  label              175341 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 17.1 MB

#### 1.1. Renomeando os atributos
---

A adequação dos nomes dos atributos é feita com o atributo `.rename()`. Para tal, há a necessidade de explicitar o parâmetro `columns` e passar como argumento os nomes antigos e novos dos atributos, em formato de `dicionário` ou `JSON`.

É feita para uma maior comodidade e compreensão no contexto de `Manipulação de Dados` e `Análise Exploratória de Dados`.

In [5]:
df = df.rename(columns={
    'dur':'duracao_conexao_seg',
    'proto':'protocolo_rede',
    'service':'servico_conexao',
    'state':'estado_conexao',
    'spkts':'num_pacotes_origem',
    'dpkts':'num_pacotes_destino',
    'sbytes':'total_bytes_origem',
    'dbytes':'total_bytes_destino',
    'rate':'taxa_pacote',
    'sload':'carga_origem',
    'dload':'carga_destino',
    'sloss':'pacotes_perdidos_origem',
    'dloss':'pacotes_perdidos_destino',
    'sinpkt':'tempo_medio_pacote_origem',
    'dinpkt':'bytes_por_pacote_destino',
    'sjit':'var_lat_pacotes_origem',
    'djit':'var_lat_pacotes_destino',
    'swin':'tamanho_janela_tcp_origem',
    'stcpb':'num_sequencia_tcp_origem',
    'dtcpb':'num_sequencia_tcp_destino',
    'dwin':'tamanho_janela_tcp_destino',
    'tcprtt':'rtt_handshake_tcp',
    'synack':'tempo_syn_synack',
    'ackdat':'tempo_synack_ack',
    'smean':'tamanho_medio_pacotes_origem',
    'dmean':'tamanho_medio_pacotes_destino',
    'trans_depth':'profundidade_transacao_http',
    'response_body_len':'tamanho_corpo_resposta_http',
    'ct_src_dport_ltm':"conexoes_recentes_ip_porta_destino",
    'ct_dst_sport_ltm':"conexoes_recentes_ip_porta_origem",
    'is_ftp_login':'ftp_autenticada',
    'ct_ftp_cmd':'num_comandos_ftp',
    'ct_flw_http_mthd':'num_metodos_http',
    'is_sm_ips_ports':'ip_porta_origem_destino_iguais',
    'attack_cat':'categoria_ataque',
    'label':'label'
})

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   duracao_conexao_seg                 175341 non-null  float32
 1   protocolo_rede                      175341 non-null  category
 2   servico_conexao                     175341 non-null  category
 3   estado_conexao                      175341 non-null  category
 4   num_pacotes_origem                  175341 non-null  int16
 5   num_pacotes_destino                 175341 non-null  int16
 6   total_bytes_origem                  175341 non-null  int32
 7   total_bytes_destino                 175341 non-null  int32
 8   taxa_pacote                         175341 non-null  float32
 9   carga_origem                        175341 non-null  float32
 10  carga_destino                       175341 non-null  float32
 11  pacotes_perdidos_origem             175341 non-null  int16
 12  pacotes_perdidos_destino            175341 non-null  int16
 13  tempo_medio_pacote_origem           175341 non-null  float32
 14  bytes_por_pacote_destino            175341 non-null  float32
 15  var_lat_pacotes_origem              175341 non-null  float32
 16  var_lat_pacotes_destino             175341 non-null  float32
 17  tamanho_janela_tcp_origem           175341 non-null  int16
 18  num_sequencia_tcp_origem            175341 non-null  int64
 19  num_sequencia_tcp_destino           175341 non-null  int64
 20  tamanho_janela_tcp_destino          175341 non-null  int16
 21  rtt_handshake_tcp                   175341 non-null  float32
 22  tempo_syn_synack                    175341 non-null  float32
 23  tempo_synack_ack                    175341 non-null  float32
 24  tamanho_medio_pacotes_origem        175341 non-null  int16
 25  tamanho_medio_pacotes_destino       175341 non-null  int16
 26  profundidade_transacao_http         175341 non-null  int16
 27  tamanho_corpo_resposta_http         175341 non-null  int32
 28  conexoes_recentes_ip_porta_destino  175341 non-null  int8
 29  conexoes_recentes_ip_porta_origem   175341 non-null  int8
 30  ftp_autenticada                     175341 non-null  int8
 31  num_comandos_ftp                    175341 non-null  int8
 32  num_metodos_http                    175341 non-null  int8
 33  ip_porta_origem_destino_iguais      175341 non-null  int8
 34  categoria_ataque                    175341 non-null  category
 35  label                               175341 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 17.1 MB

#### 1.2. Conferência de Valores e Nulos
---

In [7]:
for col in df.columns:
    print(f'\nValores do atributo {col}:\n')
    print(df[col].value_counts())
    print('\n')
    print('='*40)

Valores do atributo duracao_conexao_seg:

duracao_conexao_seg
0.000009    23031
0.000003    11751
0.000008    10634
0.000005     6690
0.000004     5026
            ...
2.013791        1
1.914309        1
3.719110        1
0.996503        1
1.557125        1
Name: count, Length: 74039, dtype: int64


========================================

Valores do atributo protocolo_rede:

protocolo_rede
tcp       79946
udp       63283
unas      12084
arp        2859
ospf       2595
          ...
netblt       98
rdp          98
igmp         18
icmp         15
rtp           1
Name: count, Length: 133, dtype: int64


========================================

Valores do atributo servico_conexao:

servico_conexao
-           94168
dns         47294
http        18724
smtp         5058
ftp-data     3995
ftp          3428
ssh          1302
pop3         1105
dhcp           94
snmp           80
ssl            56
irc            25
radius         12
Name: count, dtype: int64


========================================

Valores do atributo estado_conexao:

estado_conexao
INT    82275
FIN    77825
CON    13152
REQ     1991
RST       83
ECO       12
PAR        1
URN        1
no         1
Name: count, dtype: int64


========================================

Valores do atributo num_pacotes_origem:

num_pacotes_origem
2       85200
10      27200
12       7019
14       5051
4        4700
        ...
800         1
5184        1
1456        1
1544        1
1044        1
Name: count, Length: 480, dtype: int64


========================================

Valores do atributo num_pacotes_destino:

num_pacotes_destino
0       84282
8       17287
6       12262
2        9238
10       6825
        ...
1742        1
1656        1
404         1
2002        1
6994        1
Name: count, Length: 443, dtype: int64


========================================

Valores do atributo total_bytes_origem:

total_bytes_origem
114       39121
200       23484
146        4989
168        3578
564        3530
          ...
182785        1
51667         1
272070        1
69997         1
12601         1
Name: count, Length: 7214, dtype: int64


========================================

Valores do atributo total_bytes_destino:

total_bytes_destino
0         84282
268       11512
354        9865
178        4988
10168      2938
          ...
7924          1
59374         1
68382         1
3084          1
426483        1
Name: count, Length: 6660, dtype: int64


========================================

Valores do atributo taxa_pacote:

taxa_pacote
111111.109375    23012
333333.312500    11751
125000.000000    10616
200000.000000     6691
250000.000000     5028
                 ...
53.805313            1
108.897018           1
49.171955            1
31.468250            1
33.612648            1
Name: count, Length: 76794, dtype: int64


========================================

Valores do atributo carga_origem:

carga_origem
5.066666e+07    11997
8.888889e+07     7969
1.520000e+08     6798
5.700000e+07     6386
9.120000e+07     3634
                ...
2.885720e+05        1
6.539199e+03        1
7.185126e+03        1
6.242787e+04        1
8.826286e+03        1
Name: count, Length: 80885, dtype: int64


========================================

Valores do atributo carga_destino:

carga_destino
0.000000         84290
676163.375000       58
681992.312500       54
670433.125000       54
680688.312500       53
                 ...
8613.029297          1
914689.812500        1
129476.781250        1
9586.899414          1
4903.492188          1
Name: count, Length: 77474, dtype: int64


========================================

Valores do atributo pacotes_perdidos_origem:

pacotes_perdidos_origem
0       95448
2       30181
7       14649
3        8293
4        5802
        ...
2591        1
726         1
770         1
393         1
309         1
Name: count, Length: 409, dtype: int64


========================================

Valores do atributo pacotes_perdidos_destino:

pacotes_perdidos_destino
0       96637
1       25076
2       11603
4        6857
8        5241
        ...
200         1
281         1
140         1
999         1
3497        1
Name: count, Length: 370, dtype: int64


========================================

Valores do atributo tempo_medio_pacote_origem:

tempo_medio_pacote_origem
0.009000     26173
0.003000     12030
0.008000     11857
0.005000      7037
0.004000      5181
             ...
26.213890        1
57.217075        1
52.447525        1
57.671291        1
54.400112        1
Name: count, Length: 76050, dtype: int64


========================================

Valores do atributo bytes_por_pacote_destino:

bytes_por_pacote_destino
0.000000     84293
0.007000      3556
0.006000      1061
0.002000       794
0.008000       780
             ...
65.074280        1
10.914012        1
33.937382        1
73.691429        1
66.980568        1
Name: count, Length: 74177, dtype: int64


========================================

Valores do atributo var_lat_pacotes_origem:

var_lat_pacotes_origem
0.000000       88494
10.954517         51
10.954515         49
987.040710        48
1174.328735       42
               ...
2412.352539        1
3358.369873        1
3005.256104        1
3661.213135        1
3721.068848        1
Name: count, Length: 77390, dtype: int64


========================================

Valores do atributo var_lat_pacotes_destino:

var_lat_pacotes_destino
0.000000       93743
360.513214        23
493.566925        23
571.169983        21
453.780762        21
               ...
90.773582          1
1585.622681        1
2479.497314        1
112.418068         1
120.177727         1
Name: count, Length: 76743, dtype: int64


========================================

Valores do atributo tamanho_janela_tcp_origem:

tamanho_janela_tcp_origem
0      95395
255    79935
31         1
232        1
14         1
192        1
103        1
45         1
87         1
172        1
168        1
167        1
42         1
Name: count, dtype: int64


========================================

Valores do atributo num_sequencia_tcp_origem:

num_sequencia_tcp_origem
0             96246
4125223812        8
4223830827        6
3795074471        6
2037155331        6
              ...
556303757         1
3046870123        1
5604755           1
1932059121        1
3518776216        1
Name: count, Length: 75265, dtype: int64


========================================

Valores do atributo num_sequencia_tcp_destino:

num_sequencia_tcp_destino
0             96252
2296510182       15
3330702795       12
531409215        12
1200223257       11
              ...
246088519         1
1723342386        1
575257391         1
2472223109        1
3453092386        1
Name: count, Length: 75089, dtype: int64


========================================

Valores do atributo tamanho_janela_tcp_destino:

tamanho_janela_tcp_destino
0      96253
255    79083
244        1
70         1
48         1
37         1
40         1
Name: count, dtype: int64


========================================

Valores do atributo rtt_handshake_tcp:

rtt_handshake_tcp
0.000000    96300
0.000665      196
0.000680      179
0.000681      179
0.000664      178
            ...
0.051247        1
0.039137        1
0.044995        1
0.045137        1
0.099440        1
Name: count, Length: 43319, dtype: int64


========================================

Valores do atributo tempo_syn_synack:

tempo_syn_synack
0.000000    96300
0.000541      280
0.000539      273
0.000536      258
0.000542      248
            ...
0.011363        1
0.027147        1
0.025596        1
0.008571        1
0.036895        1
Name: count, Length: 40142, dtype: int64


========================================

Valores do atributo tempo_synack_ack:

tempo_synack_ack
0.000000    96301
0.000124     1226
0.000125     1205
0.000123     1043
0.000126     1007
            ...
0.039884        1
0.011990        1
0.037629        1
0.036566        1
0.062545        1
Name: count, Length: 37708, dtype: int64


========================================

Valores do atributo tamanho_medio_pacotes_origem:

tamanho_medio_pacotes_origem
57      40645
100     23946
53       5488
56       5293
73       5118
        ...
1357        1
1476        1
1440        1
1344        1
688         1
Name: count, Length: 1357, dtype: int64


========================================

Valores do atributo tamanho_medio_pacotes_destino:

tamanho_medio_pacotes_destino
0       84282
45      11690
44      11592
89       5296
565      2941
        ...
1390        1
561         1
1137        1
603         1
747         1
Name: count, Length: 1328, dtype: int64


========================================

Valores do atributo profundidade_transacao_http:

profundidade_transacao_http
0      157501
1       17747
2          80
4           3
3           2
5           2
39          2
80          1
155         1
163         1
172         1
Name: count, dtype: int64


========================================

Valores do atributo tamanho_corpo_resposta_http:

tamanho_corpo_resposta_http
0         164047
3924        2768
83           580
524288       386
109          333
           ...
5419           1
121            1
12836          1
18663          1
3021           1
Name: count, Length: 2386, dtype: int64


========================================

Valores do atributo conexoes_recentes_ip_porta_destino:

conexoes_recentes_ip_porta_destino
1     92793
2     24949
3      9322
16     8458
17     6325
4      4006
33     2612
18     2566
6      2011
5      1825
8      1738
14     1719
10     1564
12     1541
13     1525
34     1329
15     1313
11     1284
9      1267
7      1159
32      659
25      424
28      402
27      395
30      375
24      370
20      361
29      351
23      344
31      323
21      306
19      292
26      271
22      257
36      175
41      123
42       84
39       78
37       74
35       70
51       51
46       46
50       43
43       43
40       40
45       40
38       38
Name: count, dtype: int64


========================================

Valores do atributo conexoes_recentes_ip_porta_origem:

conexoes_recentes_ip_porta_origem
1     109640
2      16029
16     10619
17      7781
3       6945
18      3185
4       2949
14      1960
15      1862
13      1854
8       1772
11      1729
12      1704
10      1561
5       1432
9       1322
7       1146
6       1009
24       117
19        95
23        92
22        85
20        80
28        52
26        52
25        50
46        46
40        40
21        38
37        37
31        31
27        27
Name: count, dtype: int64


========================================

Valores do atributo ftp_autenticada:

ftp_autenticada
0    172774
1      2545
4        16
2         6
Name: count, dtype: int64


========================================

Valores do atributo num_comandos_ftp:

num_comandos_ftp
0    172774
1      2545
4        16
2         6
Name: count, dtype: int64


========================================

Valores do atributo num_metodos_http:

num_metodos_http
0     157501
1      16696
4        846
9         90
2         74
6         36
30        30
25        25
12        24
16        16
3          3
Name: count, dtype: int64


========================================

Valores do atributo ip_porta_origem_destino_iguais:

ip_porta_origem_destino_iguais
0    172579
1      2762
Name: count, dtype: int64


========================================

Valores do atributo categoria_ataque:

categoria_ataque
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64


========================================

Valores do atributo label:

label
1    119341
0     56000
Name: count, dtype: int64


========================================

Valores nulos geram erro de processamento, por isso devem ser tratados.

No dataset escolhido, nenhuma coluna apresentou tais valores.

In [8]:
df.isna().sum()

duracao_conexao_seg                   0
protocolo_rede                        0
servico_conexao                       0
estado_conexao                        0
num_pacotes_origem                    0
num_pacotes_destino                   0
total_bytes_origem                    0
total_bytes_destino                   0
taxa_pacote                           0
carga_origem                          0
carga_destino                         0
pacotes_perdidos_origem               0
pacotes_perdidos_destino              0
tempo_medio_pacote_origem             0
bytes_por_pacote_destino              0
var_lat_pacotes_origem                0
var_lat_pacotes_destino               0
tamanho_janela_tcp_origem             0
num_sequencia_tcp_origem              0
num_sequencia_tcp_destino             0
tamanho_janela_tcp_destino            0
rtt_handshake_tcp                     0
tempo_syn_synack                      0
tempo_synack_ack                      0
tamanho_medio_pacotes_origem          0
tamanho_medio_pacotes_destino         0
profundidade_transacao_http           0
tamanho_corpo_resposta_http           0
conexoes_recentes_ip_porta_destino    0
conexoes_recentes_ip_porta_origem     0
ftp_autenticada                       0
num_comandos_ftp                      0
num_metodos_http                      0
ip_porta_origem_destino_iguais        0
categoria_ataque                      0
label                                 0
dtype: int64

#### 1.3. Conferência de registros duplicados em todo o DataFrame
---

Manter registros completos duplicados na base de dados que será usada para testes do modelo preditivo pode levar a `overfitting`, onde o modelo acaba "decorando" padrões específicos, que pode levar a um enviezamento de respostas. Portanto, duplicatas devem ser excluídas.

No dataset, há a presença de `78519` registros duplicados.

In [9]:
df.duplicated().sum()

np.int64(78519)

#### 1.4. Conferência de valores únicos por atributo
---

O dataset possui 11 atributos que, por terem poucos valores únicos poderiam ser divididos em `categorias`:
| Atributo | Número de valores únicos |
| :---: | :---: |
| `servico_conexao` | 13 |
| `estado_conexao` | 9 |
| `tamanho_janela_tcp_origem` | 13 |
| `tamanho_janela_tcp_destino` | 7 |
| `profundidade_transacao_http` | 11 |
| `ftp_autenticada` | 4 |
| `num_comandos_ftp` | 4 |
| `num_metodos_http` | 11 |
| `ip_porta_origem_destino_iguais` | 2 |
| `categoria_ataque` | 10 |
| `label` | 2 |

Os demais atributos possuem diversos valores únicos, não podendo ser divididos e, categorias de maneira mais simples.

In [10]:
df.nunique()

duracao_conexao_seg                   74039
protocolo_rede                          133
servico_conexao                          13
estado_conexao                            9
num_pacotes_origem                      480
num_pacotes_destino                     443
total_bytes_origem                     7214
total_bytes_destino                    6660
taxa_pacote                           76794
carga_origem                          80885
carga_destino                         77474
pacotes_perdidos_origem                 409
pacotes_perdidos_destino                370
tempo_medio_pacote_origem             76050
bytes_por_pacote_destino              74177
var_lat_pacotes_origem                77390
var_lat_pacotes_destino               76743
tamanho_janela_tcp_origem                13
num_sequencia_tcp_origem              75265
num_sequencia_tcp_destino             75089
tamanho_janela_tcp_destino                7
rtt_handshake_tcp                     43319
tempo_syn_synack                      40142
tempo_synack_ack                      37708
tamanho_medio_pacotes_origem           1357
tamanho_medio_pacotes_destino          1328
profundidade_transacao_http              11
tamanho_corpo_resposta_http            2386
conexoes_recentes_ip_porta_destino       47
conexoes_recentes_ip_porta_origem        32
ftp_autenticada                           4
num_comandos_ftp                          4
num_metodos_http                         11
ip_porta_origem_destino_iguais            2
categoria_ataque                         10
label                                     2
dtype: int64

#### 1.5. Exclusão de registros duplicados
---

Manter colunas e dados desnecessários é perigoso, pois não trazem nenhum tipo de novas informações relevantes ou características que agregam valor ao modelo preditivo, mas podem ocasionar `enviesamento` e `ruídos` que podem confundí-lo e reduzir sua eficiência e confiabilidade.

O dataset possui `175341` registros no total, mas destes, `78519` são duplicados e devem, portanto, ser apagados.

In [11]:
df.duplicated().sum()

np.int64(78519)

In [12]:
df = df.drop_duplicates()

In [13]:
print(df.shape)

(96822, 36)

#### 1.6. Ajuste das classes dos atributos categóricos
---

Há a necessidade de se ajustar as classes raras, pois estas podem ser prejudiciais ao modelo, levando ao `overfitting`. Um cenário possível associar uma classe x, que apareceu apenas uma vez, a `0` ou `1`.

##### 1.6.1. Atributo protocolo_rede
---

- **Original**:

In [14]:
df['protocolo_rede'].value_counts()

protocolo_rede
tcp        75805
udp        15238
ospf         769
arp          591
unas         350
           ...
tlsp          20
xns-idp       18
igmp          15
icmp          12
rtp            1
Name: count, Length: 133, dtype: int64

- **Após limitação induzida**:

In [15]:
limite = 1000

frequencias = df['protocolo_rede'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['protocolo_rede'] = df['protocolo_rede'].astype('str').replace(protocolos_raros, 'outros')

print(df['protocolo_rede'].value_counts())

protocolo_rede
tcp       75805
udp       15238
outros     5779
Name: count, dtype: int64

##### 1.6.2. Atributo servico_conexao
---

- **Original**:

In [16]:
df['servico_conexao'].value_counts()

servico_conexao
-           57971
http        18090
dns          7181
smtp         5023
ftp-data     3282
ftp          2687
ssh          1295
pop3         1104
ssl            56
dhcp           51
snmp           45
irc            25
radius         12
Name: count, dtype: int64

- **Após limitação induzida**:

In [17]:
limite = 1000

frequencias = df['servico_conexao'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['servico_conexao'] = df['servico_conexao'].astype('str').replace(protocolos_raros, 'outros')

print(df['servico_conexao'].value_counts())

servico_conexao
-           57971
http        18090
dns          7181
smtp         5023
ftp-data     3282
ftp          2687
ssh          1295
pop3         1104
outros        189
Name: count, dtype: int64

##### 1.6.3. Atributo servico_conexao
---

- **Original**:

In [18]:
df['estado_conexao'].value_counts()

estado_conexao
FIN    74345
CON    10976
INT    10812
REQ      594
RST       83
ECO        9
PAR        1
URN        1
no         1
Name: count, dtype: int64

- **Após limitação induzida**:

In [19]:
limite = 1000

frequencias = df['estado_conexao'].value_counts()

protocolos_raros = frequencias[frequencias < limite].index

df['estado_conexao'] = df['estado_conexao'].astype('str').replace(protocolos_raros, 'outros')

print(df['estado_conexao'].value_counts())

estado_conexao
FIN       74345
CON       10976
INT       10812
outros      689
Name: count, dtype: int64

##### 1.6.4. Atributo categoria_ataque
---

- **Original**:

In [20]:
df['categoria_ataque'].value_counts()

categoria_ataque
Normal            48894
Exploits          19360
Fuzzers           14082
Reconnaissance     6000
DoS                3369
Generic            1800
Backdoor           1121
Analysis           1119
Shellcode           954
Worms               123
Name: count, dtype: int64

Não será limitado por ser um `target`. É necessário ter todos os dados detalhados desse atributo.

#### 1.7. Adequando a tipagem dos dados relativos aos atributos
---

É necessária a adequação da tipagem dos dados relativos aos atributos, para que todo o processo de `Análise Exploratória de Dados` e `Treino e Teste dos Modelos de Aprendizado Supervisionado` aconteçam da melhor maneira.

Tanto a `Matriz de Correlação de Spearman` e a biblioteca `Scikit-Learn` operam somente com valores numéricos. Em caso de haver dados das classes `str`, `object`, `datetime` e `category`, a matriz pode desconsiderá-los e o sklearn pode retornar erro.

Há a necessidade de tratar os atributos categóricos que tenham a tipagem `str` ou `object`. São muito relevantes tanto para as análises descritivas, quanto para as preditivas, por agruparem dados que possam ter grande correlação com o diagnóstico de ataque cibernético. Contudo, para serem usados, devem ser transformados em números.

Para este notebook, que tem por finalidade o `pré-processamento dos dados` que irão ser usados no desenvolvimento dos modelos preditivos, a escolha de encoding é o `OneHotEncoding`, por ser mais adequado a modelos como `Regressão Logística` e `Multi Layer Perceptron (MLP)` por não sugerir prioridade nos dados, mas aumenta a dimensionalidade.

##### 1.6.1. Encoding com OneHotEncoding
---

In [21]:
atr_categoricos = ['protocolo_rede', 'servico_conexao', 'estado_conexao', 'categoria_ataque', 'label']

In [22]:
encoder = OneHotEncoder()

dados_transformados = encoder.fit_transform(df[atr_categoricos]).toarray()

df_codificado = pd.DataFrame(dados_transformados, columns=encoder.get_feature_names_out(atr_categoricos), index=df.index
)


df_codificado

,protocolo_rede_outros,protocolo_rede_tcp,protocolo_rede_udp,servico_conexao_-,servico_conexao_dns,servico_conexao_ftp,servico_conexao_ftp-data,servico_conexao_http,servico_conexao_outros,servico_conexao_pop3,...,categoria_ataque_DoS,categoria_ataque_Exploits,categoria_ataque_Fuzzers,categoria_ataque_Generic,categoria_ataque_Normal,categoria_ataque_Reconnaissance,categoria_ataque_Shellcode,categoria_ataque_Worms,label_0,label_1
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175267,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
175277,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
175299,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
175305,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
175337,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

##### 1.6.2. Criação do df_final para uso nos modelos
---

In [23]:
df_copia = df.copy()

df_copia = df_copia.drop(columns=atr_categoricos)

atr_nao_categoricos = df_copia.columns.to_list()

df_final = pd.concat([df_copia, df_codificado], axis=1)
df_final.info()

<class 'pandas.DataFrame'>
Index: 96822 entries, 0 to 175337
Data columns (total 59 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   duracao_conexao_seg                 96822 non-null  float32
 1   num_pacotes_origem                  96822 non-null  int16
 2   num_pacotes_destino                 96822 non-null  int16
 3   total_bytes_origem                  96822 non-null  int32
 4   total_bytes_destino                 96822 non-null  int32
 5   taxa_pacote                         96822 non-null  float32
 6   carga_origem                        96822 non-null  float32
 7   carga_destino                       96822 non-null  float32
 8   pacotes_perdidos_origem             96822 non-null  int16
 9   pacotes_perdidos_destino            96822 non-null  int16
 10  tempo_medio_pacote_origem           96822 non-null  float32
 11  bytes_por_pacote_destino            96822 non-null  float32
 12  var_lat_pacotes_origem              96822 non-null  float32
 13  var_lat_pacotes_destino             96822 non-null  float32
 14  tamanho_janela_tcp_origem           96822 non-null  int16
 15  num_sequencia_tcp_origem            96822 non-null  int64
 16  num_sequencia_tcp_destino           96822 non-null  int64
 17  tamanho_janela_tcp_destino          96822 non-null  int16
 18  rtt_handshake_tcp                   96822 non-null  float32
 19  tempo_syn_synack                    96822 non-null  float32
 20  tempo_synack_ack                    96822 non-null  float32
 21  tamanho_medio_pacotes_origem        96822 non-null  int16
 22  tamanho_medio_pacotes_destino       96822 non-null  int16
 23  profundidade_transacao_http         96822 non-null  int16
 24  tamanho_corpo_resposta_http         96822 non-null  int32
 25  conexoes_recentes_ip_porta_destino  96822 non-null  int8
 26  conexoes_recentes_ip_porta_origem   96822 non-null  int8
 27  ftp_autenticada                     96822 non-null  int8
 28  num_comandos_ftp                    96822 non-null  int8
 29  num_metodos_http                    96822 non-null  int8
 30  ip_porta_origem_destino_iguais      96822 non-null  int8
 31  protocolo_rede_outros               96822 non-null  float64
 32  protocolo_rede_tcp                  96822 non-null  float64
 33  protocolo_rede_udp                  96822 non-null  float64
 34  servico_conexao_-                   96822 non-null  float64
 35  servico_conexao_dns                 96822 non-null  float64
 36  servico_conexao_ftp                 96822 non-null  float64
 37  servico_conexao_ftp-data            96822 non-null  float64
 38  servico_conexao_http                96822 non-null  float64
 39  servico_conexao_outros              96822 non-null  float64
 40  servico_conexao_pop3                96822 non-null  float64
 41  servico_conexao_smtp                96822 non-null  float64
 42  servico_conexao_ssh                 96822 non-null  float64
 43  estado_conexao_CON                  96822 non-null  float64
 44  estado_conexao_FIN                  96822 non-null  float64
 45  estado_conexao_INT                  96822 non-null  float64
 46  estado_conexao_outros               96822 non-null  float64
 47  categoria_ataque_Analysis           96822 non-null  float64
 48  categoria_ataque_Backdoor           96822 non-null  float64
 49  categoria_ataque_DoS                96822 non-null  float64
 50  categoria_ataque_Exploits           96822 non-null  float64
 51  categoria_ataque_Fuzzers            96822 non-null  float64
 52  categoria_ataque_Generic            96822 non-null  float64
 53  categoria_ataque_Normal             96822 non-null  float64
 54  categoria_ataque_Reconnaissance     96822 non-null  float64
 55  categoria_ataque_Shellcode          96822 non-null  float64
 56  categoria_ataque_Worms              96822 non-null  float64
 57  label_0                             96822 non-null  float64
 58  label_1                             96822 non-null  float64
dtypes: float32(11), float64(28), int16(9), int32(3), int64(2), int8(6)
memory usage: 30.3 MB

##### 1.6.3. Transformar valores em float64
---

In [24]:
for x in df_final.columns:
    df_final[x] = df_final[x].astype(float)
    print(f'O atributo {x} teve o tipo convertido para {df_final[x].dtype}')

df_final = df_final.copy()

O atributo duracao_conexao_seg teve o tipo convertido para float64
O atributo num_pacotes_origem teve o tipo convertido para float64
O atributo num_pacotes_destino teve o tipo convertido para float64
O atributo total_bytes_origem teve o tipo convertido para float64
O atributo total_bytes_destino teve o tipo convertido para float64
O atributo taxa_pacote teve o tipo convertido para float64
O atributo carga_origem teve o tipo convertido para float64
O atributo carga_destino teve o tipo convertido para float64
O atributo pacotes_perdidos_origem teve o tipo convertido para float64
O atributo pacotes_perdidos_destino teve o tipo convertido para float64
O atributo tempo_medio_pacote_origem teve o tipo convertido para float64
O atributo bytes_por_pacote_destino teve o tipo convertido para float64
O atributo var_lat_pacotes_origem teve o tipo convertido para float64
O atributo var_lat_pacotes_destino teve o tipo convertido para float64
O atributo tamanho_janela_tcp_origem teve o tipo convertido para float64
O atributo num_sequencia_tcp_origem teve o tipo convertido para float64
O atributo num_sequencia_tcp_destino teve o tipo convertido para float64
O atributo tamanho_janela_tcp_destino teve o tipo convertido para float64
O atributo rtt_handshake_tcp teve o tipo convertido para float64
O atributo tempo_syn_synack teve o tipo convertido para float64
O atributo tempo_synack_ack teve o tipo convertido para float64
O atributo tamanho_medio_pacotes_origem teve o tipo convertido para float64
O atributo tamanho_medio_pacotes_destino teve o tipo convertido para float64
O atributo profundidade_transacao_http teve o tipo convertido para float64
O atributo tamanho_corpo_resposta_http teve o tipo convertido para float64
O atributo conexoes_recentes_ip_porta_destino teve o tipo convertido para float64
O atributo conexoes_recentes_ip_porta_origem teve o tipo convertido para float64
O atributo ftp_autenticada teve o tipo convertido para float64
O atributo num_comandos_ftp teve o tipo convertido para float64
O atributo num_metodos_http teve o tipo convertido para float64
O atributo ip_porta_origem_destino_iguais teve o tipo convertido para float64
O atributo protocolo_rede_outros teve o tipo convertido para float64
O atributo protocolo_rede_tcp teve o tipo convertido para float64
O atributo protocolo_rede_udp teve o tipo convertido para float64
O atributo servico_conexao_- teve o tipo convertido para float64
O atributo servico_conexao_dns teve o tipo convertido para float64
O atributo servico_conexao_ftp teve o tipo convertido para float64
O atributo servico_conexao_ftp-data teve o tipo convertido para float64
O atributo servico_conexao_http teve o tipo convertido para float64
O atributo servico_conexao_outros teve o tipo convertido para float64
O atributo servico_conexao_pop3 teve o tipo convertido para float64
O atributo servico_conexao_smtp teve o tipo convertido para float64
O atributo servico_conexao_ssh teve o tipo convertido para float64
O atributo estado_conexao_CON teve o tipo convertido para float64
O atributo estado_conexao_FIN teve o tipo convertido para float64
O atributo estado_conexao_INT teve o tipo convertido para float64
O atributo estado_conexao_outros teve o tipo convertido para float64
O atributo categoria_ataque_Analysis teve o tipo convertido para float64
O atributo categoria_ataque_Backdoor teve o tipo convertido para float64
O atributo categoria_ataque_DoS teve o tipo convertido para float64
O atributo categoria_ataque_Exploits teve o tipo convertido para float64
O atributo categoria_ataque_Fuzzers teve o tipo convertido para float64
O atributo categoria_ataque_Generic teve o tipo convertido para float64
O atributo categoria_ataque_Normal teve o tipo convertido para float64
O atributo categoria_ataque_Reconnaissance teve o tipo convertido para float64
O atributo categoria_ataque_Shellcode teve o tipo convertido para float64
O atributo categoria_ataque_Worms teve o tipo convertido para float64
O atributo label_0 teve o tipo convertido para float64
O atributo label_1 teve o tipo convertido para float64

In [25]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 96822 entries, 0 to 175337
Data columns (total 59 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   duracao_conexao_seg                 96822 non-null  float64
 1   num_pacotes_origem                  96822 non-null  float64
 2   num_pacotes_destino                 96822 non-null  float64
 3   total_bytes_origem                  96822 non-null  float64
 4   total_bytes_destino                 96822 non-null  float64
 5   taxa_pacote                         96822 non-null  float64
 6   carga_origem                        96822 non-null  float64
 7   carga_destino                       96822 non-null  float64
 8   pacotes_perdidos_origem             96822 non-null  float64
 9   pacotes_perdidos_destino            96822 non-null  float64
 10  tempo_medio_pacote_origem           96822 non-null  float64
 11  bytes_por_pacote_destino            96822 non-null  float64
 12  var_lat_pacotes_origem              96822 non-null  float64
 13  var_lat_pacotes_destino             96822 non-null  float64
 14  tamanho_janela_tcp_origem           96822 non-null  float64
 15  num_sequencia_tcp_origem            96822 non-null  float64
 16  num_sequencia_tcp_destino           96822 non-null  float64
 17  tamanho_janela_tcp_destino          96822 non-null  float64
 18  rtt_handshake_tcp                   96822 non-null  float64
 19  tempo_syn_synack                    96822 non-null  float64
 20  tempo_synack_ack                    96822 non-null  float64
 21  tamanho_medio_pacotes_origem        96822 non-null  float64
 22  tamanho_medio_pacotes_destino       96822 non-null  float64
 23  profundidade_transacao_http         96822 non-null  float64
 24  tamanho_corpo_resposta_http         96822 non-null  float64
 25  conexoes_recentes_ip_porta_destino  96822 non-null  float64
 26  conexoes_recentes_ip_porta_origem   96822 non-null  float64
 27  ftp_autenticada                     96822 non-null  float64
 28  num_comandos_ftp                    96822 non-null  float64
 29  num_metodos_http                    96822 non-null  float64
 30  ip_porta_origem_destino_iguais      96822 non-null  float64
 31  protocolo_rede_outros               96822 non-null  float64
 32  protocolo_rede_tcp                  96822 non-null  float64
 33  protocolo_rede_udp                  96822 non-null  float64
 34  servico_conexao_-                   96822 non-null  float64
 35  servico_conexao_dns                 96822 non-null  float64
 36  servico_conexao_ftp                 96822 non-null  float64
 37  servico_conexao_ftp-data            96822 non-null  float64
 38  servico_conexao_http                96822 non-null  float64
 39  servico_conexao_outros              96822 non-null  float64
 40  servico_conexao_pop3                96822 non-null  float64
 41  servico_conexao_smtp                96822 non-null  float64
 42  servico_conexao_ssh                 96822 non-null  float64
 43  estado_conexao_CON                  96822 non-null  float64
 44  estado_conexao_FIN                  96822 non-null  float64
 45  estado_conexao_INT                  96822 non-null  float64
 46  estado_conexao_outros               96822 non-null  float64
 47  categoria_ataque_Analysis           96822 non-null  float64
 48  categoria_ataque_Backdoor           96822 non-null  float64
 49  categoria_ataque_DoS                96822 non-null  float64
 50  categoria_ataque_Exploits           96822 non-null  float64
 51  categoria_ataque_Fuzzers            96822 non-null  float64
 52  categoria_ataque_Generic            96822 non-null  float64
 53  categoria_ataque_Normal             96822 non-null  float64
 54  categoria_ataque_Reconnaissance     96822 non-null  float64
 55  categoria_ataque_Shellcode          96822 non-null  float64
 56  categoria_ataque_Worms              96822 non-null  float64
 57  label_0                             96822 non-null  float64
 58  label_1                             96822 non-null  float64
dtypes: float64(59)
memory usage: 44.3 MB

### 2. Normalização de Features
---

Como visto no `Notebook de Explicação de Pré-Processamento e Análise Exploratória de Dados`, a distribuição dos dados se mostra `não normal`. Desta forma, o tipo de normalização mais adequado, de modo geral, é o `RobustScaler`, que é baseado em `IQR`. Contudo, também foi utilizado `MinMaxScaler` em alguns atributos:

1. `RobustScaler`:
   - Utilizado em atributos volumétricos: Bytes, Pacotes, Duração, Carga, RTT e Variância de Latência;
   - Presença de muitos outliers e variância muito expressiva, já que dados de volume brutos de rede são naturalmente assimétricos. Uma conexão normal pode trocar 500 bytes, enquanto um download legítimo ou um ataque de negação de serviço (DoS/DDoS) pode transferir 12 milhões de bytes na mesma janela de tempo;
   - Utiliza a Mediana e o Intervalo Interquartil (IQR) em vez da média e do máximo. Isso garante que a massa de dados normais fique bem distribuída em torno de zero, enquanto os picos (outliers) ganham valores proporcionalmente altos (como 5415.28). O modelo consegue diferenciar um tráfego comum de uma anomalia sem perder a sensibilidade dos dados menores.

2. `MinMaxScaler`:
    - Utilizado em atributos de aplicação e contagem: Métodos HTTP, Comandos FTP, Conexões Recentes, Tamanho de Janela TCP e Flags;
    - Limites bem definidos: essas variáveis possuem tetos previsíveis e controlados pelo protocolo. O número de métodos HTTP disparados em uma única sessão varia em uma escala menor. O tamanho da janela TCP possui um limite rígido do sistema (0 a 255). Não existem outliers muito grandes e distantes;
    - O MinMaxScaler mapeia com eficiência o menor valor para 0.0 e o maior valor real (seja 4, 30 ou 255) para 1.0, por conta da previsibilidade das variáveis. Isso traz todas as contagens para a mesma ordem de grandeza do restante do dataset de forma mais homogênea.

#### 2.1. Separando os atributos
---

##### 2.1.1. Atributos não categóricos
---

In [26]:
atr_nao_categoricos = df.drop(columns=atr_categoricos).columns.to_list()

##### 2.1.2. Atributos para RobustScaler
---

In [27]:
colunas_para_remover = atr_categoricos + [
    'tamanho_janela_tcp_origem', 'tamanho_janela_tcp_destino', 'profundidade_transacao_http',
    'tamanho_corpo_resposta_http', 'conexoes_recentes_ip_porta_destino', 'conexoes_recentes_ip_porta_origem',
    'ftp_autenticada', 'num_comandos_ftp', 'num_metodos_http', 'ip_porta_origem_destino_iguais'
]
atr_robust_scaler = df.drop(columns=colunas_para_remover).columns.to_list()

##### 2.1.3. Atributos para MinMaxScaler
---

In [28]:
atr_min_max_scaler = df[['tamanho_janela_tcp_origem',
    'tamanho_janela_tcp_destino',
    'profundidade_transacao_http',
    'tamanho_corpo_resposta_http',
    'conexoes_recentes_ip_porta_destino',
    'conexoes_recentes_ip_porta_origem',
    'ftp_autenticada',
    'num_comandos_ftp',
    'num_metodos_http',
    'ip_porta_origem_destino_iguais']].columns.to_list()

#### 2.2. Normalizando atributos
---

##### 2.2.1. RobustScaler
---

In [29]:
# Instancia o escalonador
escalonador_robusto = RobustScaler()

# O escalonador aprende com a sua base de dados -> necessário para salvar o aprendizado do escalonador
escalonador_robusto.fit(df_final[atr_robust_scaler])

# Transforma o bloco de colunas inteiro de uma vez para respeitar o formato esperado pelo Scikit-Learn e evitar erros de dimensionalidade no .transform()
df_robust_transformado = pd.DataFrame(
    escalonador_robusto.transform(df_final[atr_robust_scaler]), 
    columns=atr_robust_scaler, 
    index=df_final.index
)

# Iteração por todos os atributos, mostrando os valores antes e depois da Normalização e apenas transformando os dados que já foram aprendidos
for col in atr_robust_scaler:

    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'\n\n   -> Atributo {col.upper()}:\n')
    print(f'O atributo {col} possui amplitude entre {valor_min} e {valor_max} e magnitude {faixa} antes da Normalização com {escalonador_robusto}.\n')
    
    
    df_final.loc[:, col] = df_robust_transformado[col]
    
    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'O atributo {col} foi normalizado. Sua amplitude atual está entre {valor_min} e {valor_max}. Já sua magnitude é {faixa}.\n')

# Consolida as alterações no DataFrame e previne o aviso "PerformanceWarning: DataFrame is highly fragmented"
df_final = df_final.copy()

   -> Atributo DURACAO_CONEXAO_SEG:

O atributo duracao_conexao_seg possui amplitude entre 0.0 e 59.9999885559082 e magnitude 59.9999885559082 antes da Normalização com RobustScaler().

O atributo duracao_conexao_seg foi normalizado. Sua amplitude atual está entre -0.44357456734279826 e 59.43035021560755. Já sua magnitude é 59.87392478295035.



   -> Atributo NUM_PACOTES_ORIGEM:

O atributo num_pacotes_origem possui amplitude entre 1.0 e 9616.0 e magnitude 9615.0 antes da Normalização com RobustScaler().

O atributo num_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.5625 e 600.375. Já sua magnitude é 600.9375.



   -> Atributo NUM_PACOTES_DESTINO:

O atributo num_pacotes_destino possui amplitude entre 0.0 e 10974.0 e magnitude 10974.0 antes da Normalização com RobustScaler().

O atributo num_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.5 e 685.375. Já sua magnitude é 685.875.



   -> Atributo TOTAL_BYTES_ORIGEM:

O atributo total_bytes_origem possui amplitude entre 28.0 e 12965233.0 e magnitude 12965205.0 antes da Normalização com RobustScaler().

O atributo total_bytes_origem foi normalizado. Sua amplitude atual está entre -0.42606516290726815 e 5415.2819548872185. Já sua magnitude é 5415.708020050126.



   -> Atributo TOTAL_BYTES_DESTINO:

O atributo total_bytes_destino possui amplitude entre 0.0 e 14655550.0 e magnitude 14655550.0 antes da Normalização com RobustScaler().

O atributo total_bytes_destino foi normalizado. Sua amplitude atual está entre -0.20493247210804463 e 4302.6576629477395. Já sua magnitude é 4302.862595419848.



   -> Atributo TAXA_PACOTE:

O atributo taxa_pacote possui amplitude entre 0.0 e 1000000.0 e magnitude 1000000.0 antes da Normalização com RobustScaler().

O atributo taxa_pacote foi normalizado. Sua amplitude atual está entre -0.02273333602547066 e 356.06816390032577. Já sua magnitude é 356.0908972363512.



   -> Atributo CARGA_ORIGEM:

O atributo carga_origem possui amplitude entre 0.0 e 5988000256.0 e magnitude 5988000256.0 antes da Normalização com RobustScaler().

O atributo carga_origem foi normalizado. Sua amplitude atual está entre -0.057231631081325486 e 9427.744951992034. Já sua magnitude é 9427.802183623115.



   -> Atributo CARGA_DESTINO:

O atributo carga_destino possui amplitude entre 0.0 e 22422730.0 e magnitude 22422730.0 antes da Normalização com RobustScaler().

O atributo carga_destino foi normalizado. Sua amplitude atual está entre -0.016328903360192524 e 36.700989512499405. Já sua magnitude é 36.717318415859594.



   -> Atributo PACOTES_PERDIDOS_ORIGEM:

O atributo pacotes_perdidos_origem possui amplitude entre 0.0 e 4803.0 e magnitude 4803.0 antes da Normalização com RobustScaler().

O atributo pacotes_perdidos_origem foi normalizado. Sua amplitude atual está entre -0.4 e 960.2. Já sua magnitude é 960.6.



   -> Atributo PACOTES_PERDIDOS_DESTINO:

O atributo pacotes_perdidos_destino possui amplitude entre 0.0 e 5484.0 e magnitude 5484.0 antes da Normalização com RobustScaler().

O atributo pacotes_perdidos_destino foi normalizado. Sua amplitude atual está entre -0.3333333333333333 e 913.6666666666666. Já sua magnitude é 914.0.



   -> Atributo TEMPO_MEDIO_PACOTE_ORIGEM:

O atributo tempo_medio_pacote_origem possui amplitude entre 0.0 e 84371.4921875 e magnitude 84371.4921875 antes da Normalização com RobustScaler().

O atributo tempo_medio_pacote_origem foi normalizado. Sua amplitude atual está entre -0.36133865318408365 e 1065.6872198364367. Já sua magnitude é 1066.0485584896207.



   -> Atributo BYTES_POR_PACOTE_DESTINO:

O atributo bytes_por_pacote_destino possui amplitude entre 0.0 e 56716.82421875 e magnitude 56716.82421875 antes da Normalização com RobustScaler().

O atributo bytes_por_pacote_destino foi normalizado. Sua amplitude atual está entre -0.3478855071532177 e 642.4881304966716. Já sua magnitude é 642.8360160038249.



   -> Atributo VAR_LAT_PACOTES_ORIGEM:

O atributo var_lat_pacotes_origem possui amplitude entre 0.0 e 1460480.0 e magnitude 1460480.0 antes da Normalização com RobustScaler().

O atributo var_lat_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.34416657687734703 e 313.6919244498777. Já sua magnitude é 314.03609102675506.



   -> Atributo VAR_LAT_PACOTES_DESTINO:

O atributo var_lat_pacotes_destino possui amplitude entre 0.0 e 289388.28125 e magnitude 289388.28125 antes da Normalização com RobustScaler().

O atributo var_lat_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.400681236510594 e 1419.5432631173535. Já sua magnitude é 1419.943944353864.



   -> Atributo NUM_SEQUENCIA_TCP_ORIGEM:

O atributo num_sequencia_tcp_origem possui amplitude entre 0.0 e 4294958913.0 e magnitude 4294958913.0 antes da Normalização com RobustScaler().

O atributo num_sequencia_tcp_origem foi normalizado. Sua amplitude atual está entre -0.5597790686381059 e 0.9974645235758729. Já sua magnitude é 1.557243592213979.



   -> Atributo NUM_SEQUENCIA_TCP_DESTINO:

O atributo num_sequencia_tcp_destino possui amplitude entre 0.0 e 4294881924.0 e magnitude 4294881924.0 antes da Normalização com RobustScaler().

O atributo num_sequencia_tcp_destino foi normalizado. Sua amplitude atual está entre -0.558730231133571 e 1.001638278480071. Já sua magnitude é 1.560368509613642.



   -> Atributo RTT_HANDSHAKE_TCP:

O atributo rtt_handshake_tcp possui amplitude entre 0.0 e 2.518893003463745 e magnitude 2.518893003463745 antes da Normalização com RobustScaler().

O atributo rtt_handshake_tcp foi normalizado. Sua amplitude atual está entre -0.009828122445103204 e 19.24055182089483. Já sua magnitude é 19.250379943339933.



   -> Atributo TEMPO_SYN_SYNACK:

O atributo tempo_syn_synack possui amplitude entre 0.0 e 2.1003520488739014 e magnitude 2.1003520488739014 antes da Normalização com RobustScaler().

O atributo tempo_syn_synack foi normalizado. Sua amplitude atual está entre -0.016261070130149765 e 31.23165475574871. Já sua magnitude é 31.24791582587886.



   -> Atributo TEMPO_SYNACK_ACK:

O atributo tempo_synack_ack possui amplitude entre 0.0 e 1.5208840370178223 e magnitude 1.5208840370178223 antes da Normalização com RobustScaler().

O atributo tempo_synack_ack foi normalizado. Sua amplitude atual está entre -0.00403792688985175 e 24.859196170876466. Já sua magnitude é 24.863234097766316.



   -> Atributo TAMANHO_MEDIO_PACOTES_ORIGEM:

O atributo tamanho_medio_pacotes_origem possui amplitude entre 28.0 e 1504.0 e magnitude 1476.0 antes da Normalização com RobustScaler().

O atributo tamanho_medio_pacotes_origem foi normalizado. Sua amplitude atual está entre -0.7534246575342466 e 19.465753424657535. Já sua magnitude é 20.21917808219178.



   -> Atributo TAMANHO_MEDIO_PACOTES_DESTINO:

O atributo tamanho_medio_pacotes_destino possui amplitude entre 0.0 e 1458.0 e magnitude 1458.0 antes da Normalização com RobustScaler().

O atributo tamanho_medio_pacotes_destino foi normalizado. Sua amplitude atual está entre -0.5925925925925926 e 10.207407407407407. Já sua magnitude é 10.8.

##### 2.2.2. MinMaxScaler
---

In [30]:
# Instancia o escalonador
escalonador_minmax = MinMaxScaler()

# O escalonador aprende com a sua base de dados -> necessário para salvar o aprendizado do escalonador
escalonador_minmax.fit(df_final[atr_min_max_scaler])

# Transforma o bloco de colunas inteiro de uma vez para respeitar o formato esperado pelo Scikit-Learn e evitar erros de dimensionalidade no .transform()
df_minmax_transformado = pd.DataFrame(
    escalonador_minmax.transform(df_final[atr_min_max_scaler]), 
    columns=atr_min_max_scaler, 
    index=df_final.index
)

# Iteração por todos os atributos, mostrando os valores antes e depois da Normalização e apenas transformando os dados que já foram aprendidos
for col in atr_min_max_scaler:

    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'\n\n   -> Atributo {col.upper()}:\n')
    print(f'O atributo {col} possui amplitude entre {valor_min} e {valor_max} e magnitude {faixa} antes da Normalização com {escalonador_minmax}.\n')
    
    df_final.loc[:, col] = df_minmax_transformado[col]
    
    _, valor_min, valor_max, _, _, faixa = pm.gerar_dispersao(df_final, col)
    print(f'O atributo {col} foi normalizado. Sua amplitude atual está entre {valor_min} e {valor_max}. Já sua magnitude é {faixa}.\n')

# Consolida as alterações no DataFrame e previne o aviso "PerformanceWarning: DataFrame is highly fragmented"
df_final = df_final.copy()

   -> Atributo TAMANHO_JANELA_TCP_ORIGEM:

O atributo tamanho_janela_tcp_origem possui amplitude entre 0.0 e 255.0 e magnitude 255.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_janela_tcp_origem foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo TAMANHO_JANELA_TCP_DESTINO:

O atributo tamanho_janela_tcp_destino possui amplitude entre 0.0 e 255.0 e magnitude 255.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_janela_tcp_destino foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo PROFUNDIDADE_TRANSACAO_HTTP:

O atributo profundidade_transacao_http possui amplitude entre 0.0 e 172.0 e magnitude 172.0 antes da Normalização com MinMaxScaler().

O atributo profundidade_transacao_http foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo TAMANHO_CORPO_RESPOSTA_HTTP:

O atributo tamanho_corpo_resposta_http possui amplitude entre 0.0 e 6558056.0 e magnitude 6558056.0 antes da Normalização com MinMaxScaler().

O atributo tamanho_corpo_resposta_http foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo CONEXOES_RECENTES_IP_PORTA_DESTINO:

O atributo conexoes_recentes_ip_porta_destino possui amplitude entre 1.0 e 51.0 e magnitude 50.0 antes da Normalização com MinMaxScaler().

O atributo conexoes_recentes_ip_porta_destino foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo CONEXOES_RECENTES_IP_PORTA_ORIGEM:

O atributo conexoes_recentes_ip_porta_origem possui amplitude entre 1.0 e 46.0 e magnitude 45.0 antes da Normalização com MinMaxScaler().

O atributo conexoes_recentes_ip_porta_origem foi normalizado. Sua amplitude atual está entre 0.0 e 1.0000000000000002. Já sua magnitude é 1.0000000000000002.



   -> Atributo FTP_AUTENTICADA:

O atributo ftp_autenticada possui amplitude entre 0.0 e 4.0 e magnitude 4.0 antes da Normalização com MinMaxScaler().

O atributo ftp_autenticada foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo NUM_COMANDOS_FTP:

O atributo num_comandos_ftp possui amplitude entre 0.0 e 4.0 e magnitude 4.0 antes da Normalização com MinMaxScaler().

O atributo num_comandos_ftp foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo NUM_METODOS_HTTP:

O atributo num_metodos_http possui amplitude entre 0.0 e 30.0 e magnitude 30.0 antes da Normalização com MinMaxScaler().

O atributo num_metodos_http foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.



   -> Atributo IP_PORTA_ORIGEM_DESTINO_IGUAIS:

O atributo ip_porta_origem_destino_iguais possui amplitude entre 0.0 e 1.0 e magnitude 1.0 antes da Normalização com MinMaxScaler().

O atributo ip_porta_origem_destino_iguais foi normalizado. Sua amplitude atual está entre 0.0 e 1.0. Já sua magnitude é 1.0.

##### 2.2.3. Salvando os escalonadores para serem usados com o dataset de teste
---

- **RobustScaler**:

In [31]:
joblib.dump(escalonador_robusto, '../escalonadores/escalonador_robusto.pkl')

['../escalonadores/escalonador_robusto.pkl']

- **MinMaxScaler**:

In [32]:
joblib.dump(escalonador_minmax, '../escalonadores/escalonador_minmax.pkl')

['../escalonadores/escalonador_minmax.pkl']

## E) Criação do Dataset Pré-processado de Treino
---

Este dataset será usado treino dos modelos preditivos.

In [33]:
df.to_parquet('../../dataset/pre_processado/treino_pre_processado.parquet')